### ISSUE TITLE
Keyframes not working?

### ISSUE THREAD

**Issue by zbouslikhin** [garronej/tss-react#104]
Hello, 

So far, using tss-react has been very enjoyable. Thanks for the great work!

When migrating from Material-ui v4 to mui v5, some animations in my application stopped working. Took a closer look at it and it looks like `@keyframes` don't work:

```js
export const Status = observer(() => {
        const { classes } = useStyles()
	return (
		<Tooltip title={tooltipText} placement='bottom'>
			<div >
				<FaCogs className={classes.flicker} />
			</div>
		</Tooltip>
	)
})

const useStyles = makeStyles()((theme) =>
	({
        "@keyframes flicker": {
			'0%': {
				transform: 'scale(1, 1)',
			},
			'50%': {
				transform: 'scale(2, 2)',
			},
			'100%': {
				transform: 'scale(1, 1)',
			},
		},
        flicker: {
			animationName: '$flicker',
			animationDuration: '500ms',
			animationIterationCount: 2,
			animationDirection: 'alternate',
			animationTimingFunction: 'ease-in-out',
			animationPlayState: 'running',
		}
    }));
```

Any help would be much appreciated!

**Comment by garronej** [comment]
Hey @zbouslikhin,  
Thanks for the encouragement.  
I don't think it work like this indeed maybe I sloud make it work this way but in the meantime this is how you are expected to work with keyframes in TSS:

**Comment by garronej** [comment]
Feel free to reopen if you need futher assistance
