### ISSUE TITLE
Alternative values disappear in production build

### ISSUE THREAD

**Issue by daniel-rabe** [garronej/tss-react#110]
example:

```
const useTopToolbarStyles = makeStyles({ name: 'TopToolbar' })({
    root: {
        backgroundColor: [
            'red', 'blue', 'green'
        ]
    },
});
```

will result in something like:

```
.tss-custom-1h1gr7u-TopToolbar-root {
    background-color: red;
    background-color: blue;
    background-color: green;
}
```

but only while i do develop-builds

in production i only get:

```
.tss-custom-1h1gr7u-TopToolbar-root {
    background-color: green;
}
```

(always just the last item of the array)

We use mui 5.8.1, tss-react 3.7.0 and webpack ^5.73.0

**Comment by garronej** [comment]
Hi @daniel-rabe thanks for reaching out,    
What do you expect to be the correct output?

**Comment by daniel-rabe** [comment]
i would expect no difference between develop and production build, the variant with multiple alternatives is what we need so browser/os takes the first valid value.

eg.
```
margin-top: 10px; // very old browser
margin-top: constant(safe-area-inset-top); // old safari
margin-top: env(safe-area-inset-top); // modern browsers
```

**Comment by garronej** [comment]
Thanks for the precision.  
Well I wasn't aware of this feature (ability to provide alternative values) but I think that it's something related to [`@emotion`](https://emotion.sh/).  
`tss-react` is a wrapper around emotion.  
If I'm wrong and you think I can do something about it do not hesitate to get back to me.  

Best regards

**Comment by garronej** [comment]
Please feel free to reopen if you have more insight on this
