### ISSUE TITLE
Breaking changes in V4?

### ISSUE THREAD

**Issue by nullberri** [garronej/tss-react#111]
I see the major version has incremented but there doesn't seem to be any breaking changes listed in the release changelog or the release section. 

Were there any breaking changes? If not, why was the major version changed?

**Comment by garronej** [comment]
Hi @nullberri,  
Here is the migration guide from v3 to v4: https://docs.tss-react.dev/update-to-v4

**Comment by nullberri** [comment]
@garronej  Thank you i see i missed the first line of the readme 😅.
