### ISSUE TITLE
Classes type issue with Record<string, unknown>

### ISSUE THREAD

**Issue by onlyreddy** [garronej/tss-react#119]
Hi,

Thanks for creating the tss-react package.

Recently I started migration from v3 to v4 and followed related docs about it. But facing some issues related to **classes** types.

![image](https://user-images.githubusercontent.com/16205943/192773030-b6fbf62b-b654-4496-bed6-5af27da29d42.png)

Then I modified my component interface so that it can extend the classes as unknown by the below way.

`export interface ComponentProps extends React.HTMLAttributes<HTMLDivElement>, Record<string, unknown> 
{
  className?: string;
  classes?: Partial<ReturnType<typeof useStyles>['classes']>;
}`

Then my problem got solved. After that, I released my package so that other devs can use it. Once they started using it, some types got broken because we are extending the interface with unknown. Now most of them are extending to unknown even though I added the proper type. If I remove the extends of Record<strings, unknown> from the interface then everything is working but I can't do that because tss-react needs **classes** as `Record<string, unknown>`.

![image](https://user-images.githubusercontent.com/16205943/192774006-68f653de-5eeb-4e38-bf29-25f170f9defb.png)

Is there any alternative way to pass the **classes** type?

**Comment by garronej** [comment]
Hi @onlyreddy,  
It's hard for me to help with so little code that I can look at.  
Would you copy pase the entire relevent files (removing the bits with sensitive company information).  

Best

**Comment by garronej** [comment]
@onlyreddy I offer you two fixes:  

The clean one (that involves some refactoring):   

![image](https://user-images.githubusercontent.com/6702424/192793010-3291c4a2-a6a2-4a08-87c8-7d2719d007d3.png)

The quick and dirty:  

![image](https://user-images.githubusercontent.com/6702424/192793211-8f8dcf81-0a8b-4b58-9373-470f00b17e06.png)

Best,

**Comment by onlyreddy** [comment]
@garronej 

Thanks for the update, I'm going with the dirty way approach. 

Do I except any fix from your side in the future?

**Comment by garronej** [comment]
After thinking about it, this problem is only related to extending `React.HTMLAttributes` which is a very specific usecase.  

I think merging users classes with internal classes only make sence where there is more than just `root`.  

In your component I would remove the `classes` prop or simply apply it like  `className={cx(classes.root, props.classes?.root, className)}`.   

I close this isue, reopen if you have any say on this.
