### ISSUE TITLE
Cannot apply css in MUI using className

### ISSUE THREAD

**Issue by phamduytien1805** [garronej/tss-react#121]
className not working in some MUI's components. Ex: Popper, MenuItem.

```tsx
import { makeStyles } from 'tss-react/mui';
const useStyles = makeStyles()((theme) => ({
  menuItem: {
     margin: theme.spacing(1)
  },
  avatar: {
    minWidth: 40,
    fontSize: theme.fontSize.normal,
  },
}));

  const classes = useStyles();

 <MenuItem
    className= { classes.menuItem}
    onClick={(e) => handleClose(e, item)}
    key={index}>
      {item.userMenu.title}
 </MenuItem>
```
But it works with Avatar components.

**Comment by garronej** [comment]
Hey @phamduytien1805,  
Thanks for reporting,  

Does it work if you add `!important`? (Just to know if it's a priority problem)

**Comment by phamduytien1805** [comment]
> 

Sorry it's my mistake. It must be `{ classes } = useStyle();` . Anw tks for reply

**Comment by garronej** [comment]
No problem you are wellcome.  
(TypeScript for the win)
