### ISSUE TITLE
withStyles ignores "name" for class-components

### ISSUE THREAD

**Issue by daniel-rabe** [garronej/tss-react#132]
```
withStyles(ClassComponent, Styles, { name: 'some-name')
```

results in classname including "ClassComponent" instead of "some-name"

https://codesandbox.io/s/floral-water-k38ms4?file=/src/index.tsx

also in production-builds with code like this sometimes the classname includes "$b" or similar string with "$" at the position where "some-name"/"ClassComponent" is in develop-builds, breaking the whole style of the component

**Comment by garronej** [comment]
Thanks for reporting and thanks for the playground

**Comment by garronej** [comment]
Sorry this is an embarassing bug indeed.  
It's fixed in v4.4.5.  
My bad for not reviewing PRs carfully enough.  

Best regards
