### ISSUE TITLE
Doc link broken on website

### ISSUE THREAD

**Issue by ewanmellor** [garronej/tss-react#133]
The link `Equivalent for $ syntax` > `Check the doc` on https://www.tss-react.dev/ goes to https://docs.tss-react.dev/nested-selectors-ex-usd-syntax, which does not exist.  It should be https://docs.tss-react.dev/nested-selectors.

**Comment by garronej** [comment]
Thank you for reporting!

**Comment by santimc** [comment]
in the same vain, on [https://docs.tss-react.dev/ssr/next.js#make-mui-and-tss-use-different-caches](https://docs.tss-react.dev/ssr/next.js#make-mui-and-tss-use-different-caches), on the app router section, its missing the `import { TssCacheProvider } from "tss-react";`

**Comment by garronej** [comment]
Thanks for reporting @santimc, I just fixed it!
