### ISSUE TITLE
MUI integration not working in production build

### ISSUE THREAD

**Issue by raegen** [garronej/tss-react#136]
"@mui/material": "^5.10.14",
"tss-react": "^4.4.4"

So, here's the deal boys, per [your docs](https://docs.tss-react.dev/mui-theme-styleoverrides), mui theme integration is supposed to work out of the box, but this doesn't seem to be the case. Here's a simple example showcasing the issue.

```typescript
import { useTheme, ThemeProvider, Theme } from '@mui/material';
import { makeStyles } from 'tss-react/mui';

const useStyles = makeStyles<Theme>()((tssTheme, muiTheme) => {
  console.log(tssTheme, muiTheme, tssTheme === muiTheme);
  // spoiler alert: tssTheme !== muiTheme, what's more, there's barely any similarity between the two
  return {
    ...some styles
  }
})

const ChildComponent = () => {
  const theme = useTheme();
  const { classes } = useStyles(theme); // I passed the mui provided theme as props for easier comparison.
  console.log(theme);
}

const ParentComponent = () => <ThemeProvider theme={{ makeStyles: 'Wont load me in production', useTheme: 'Will load me in production' } as unknown as Theme}>
    <ChildComponent />
  </ThemeProvider>
```
The theme in makeStyles seems to be the default mui theme.

**Comment by garronej** [comment]
Problem solved?

**Comment by sjdemartini** [comment]
I'm having this exact same problem, where `tss-react`'s `makeStyles`'s version of `theme` is the default MUI theme, while MUI's `useTheme` returns the _actual_/correct theme that was set in `<ThemeProvider />`. @raegen did you figure out a fix or workaround for this? 

If not, @garronej, do you have any ideas why this would happen? My setup is fairly similar to the example above, where my test app simply does `<ThemeProvider theme={theme}>...</ThemeProvider>`, and it's installing and importing my package that used `tss-react/mui`'s `makeStyles` separately. My test app does not have its own version of `tss-react`. I followed the package definitions suggested here https://docs.tss-react.dev/publish-a-module-that-uses-tss. (My package is not yet published, but I hope to publish it soon, and this would be a blocker for it rolling it, of course.) Thanks in advance!

**Comment by garronej** [comment]
Hello @sjdemartini,

The issue you're experiencing might stem from your module not utilizing the same MUI distribution. MUI, akin to tss-react, provides both ESM and CJS distributions. It's likely that your module uses `node_modules/@mui/material` while the main module operates on `node_modules/@mui/material/esm`.

The concurrent existence of these two module systems often poses challenges for NPM module publishers. A viable solution is to publish your module in both ESM and CJS formats.

It's crucial to specify the exports for both ESM and CJS (for require/import). You can refer to this example here:
https://github.com/garronej/tss-react/blob/f12238858b401a1c5a14538c5148ea1fd2fa9845/package.json#L9-L51

Alternatively, you can use a wildcard as demonstrated here:
https://github.com/garronej/tsafe/blob/6d08839c3b0695edbc3443d21b256043cd98787b/package.json#L67-L78

Remember to compile for both ESM and CJS: 
https://github.com/garronej/tss-react/blob/f12238858b401a1c5a14538c5148ea1fd2fa9845/package.json#L54

A recommended approach is to maintain a separate `tsconfig.json` file for CJS and a `tsconfig.esm.json` for ESM, where the latter extends the former. Refer to these examples: 
- [CJS](https://github.com/garronej/tss-react/blob/main/tsconfig.json) 
- [ESM](https://github.com/garronej/tss-react/blob/main/tsconfig.json)

For your convenience, I have a project starter specifically designed for bootstrapping NPM modules: 
https://github.com/garronej/ts-ci  

I hope this guidance proves useful. Please let me know how it works out for you.

**Comment by sjdemartini** [comment]
Hm, I take it back, it's still not working properly in my test app that uses `link:` to install my package that uses `tss-react`. The `theme` is correct/consistent with MUI's `useTheme` function, when called from inside my app and from inside my imported package in my app. (i.e. both the app code and external package code both match the `theme` used with `<ThemeProvider />`.) But for `tss-react`'s `makeStyles` styles specifically, the `theme` is always the default, for the usage of `makeStyles` in the imported package. The `tss-react` styles do not update when I change the `theme` passed to the `ThemeProvider`, though other MUI styles do. 

I am using ES modules for both my test app and my package. Compiling to CJS didn't seem to make a difference, and I've had the [TS `esModuleInterop` option](https://www.typescriptlang.org/tsconfig#esModuleInterop) set to true as well. 😕

**Comment by garronej** [comment]
> Understanding the Implications of Using Vite/Rollup for Library Building

While bundling a module might appear to be a good strategy, it's generally seen as less than ideal. The best practice is to reserve bundling for the final application, not the libraries. It appears there might be a complication with your current bundle, possibly due to the inclusion of MUI. This could result in duplicate copies of MUI within your final application. If this is happening, they won't be sharing the same context.

Bundling is primarily the responsibility of the final application. When a library is bundled, it restricts the end-user's ability to selectively choose components from your library. Moreover, it can also lead to unnecessary inclusion of dependencies that could have otherwise been deduplicated.

> Module-level Directives and Bundling Issues: "use client"  

The error message you've encountered is a clear indication that you're bundling `tss-react`. If you are getting this message while building your library, we have our explaination.  

> Hm, I take it back, it's still not working properly in my test app that uses

However, there's no need to feel disheartened. We will work through this together. If you could provide a link to your project, I'd be able to better diagnose the problem.

Please don't take my comments as overly critical. I've known many skilled developers who have made similar errors when first attempting to publish modules. The reality is that there's a scarcity of comprehensive resources that effectively explain how to publish NPM modules. Most of us, including myself, have had to learn through a process of trial and error.

**Comment by sjdemartini** [comment]
Thanks again garronej, super helpful comments, and you were correct about the issues! I have a clearer understanding now of how the building/bundling/publishing processes work. For what it's worth, I was thinking the Vite+rollup-based bundling approach was sensible based on a couple other examples I'd seen (such as [`mui-datatables`](https://github.com/gregnb/mui-datatables/blob/e09c39cb3c5713c7c157845b3d3e4b7d77c77649/package.json#L21) which uses `tss-react`, and [`react-hook-form`](https://github.com/react-hook-form/react-hook-form/blob/bc0f67ed1928b688cfc3d1c7c8aabee0647c9ae4/package.json#L32-L33) which is a fairly popular library I've used), but it makes sense to simplify and generate the publishable code using `tsc` alone, leaving bundling for the final application.

The bundling was one issue with my approach, but the other was that I was using `"my-package": "link:../"` to install my package from my separate test application (with `pnpm`). I didn't realize that `link:` does not "install" the package, but rather links the entirety of the project and its underlying `node_modules`, which contributed to having two instances of MUI (and two of React as well, which I'd previously worked around by _also_ linking React, which should have been a red flag!). I've simplified to use `file:../` instead (or can get equivalent behavior with pnpm's `workspace:../` along with [`dependenciesMeta.*.injected`](https://pnpm.io/package_json#dependenciesmetainjected)).

So with a `build` step similar to yours (packaging cjs and es separately using `tsc`), and with `file:` based install in my separate app, it's now working properly. 🙇

**Comment by garronej** [comment]
Onward and Upward! 🚀  

I'm extremely pleased that we managed to resolve this issue. Congratulations on assembling all the pieces!  

I will reference this discussion in the TSS documentation.  

Here's an additional note for those wishing to publish a module compatible with *all* environments (this doesn't specifically pertain to your library, @sjdemartini).  
- If you intend for your library to function with [node in `module` mode](https://nodejs.org/api/esm.html), there's an additional step you need to undertake. This involves renaming all `.js` files from the `esm` distribution to `.mjs`.  Also, all imports must be executed using the `.mjs` extension (`import "./foo"` -> `import "./foo.mjs"`). This is the function of the [`js2mjs` script](https://github.com/garronej/tsafe/blob/6d08839c3b0695edbc3443d21b256043cd98787b/package.json#L12).  

- Furthermore, you may wish to publish a native distribution for Deno. For this purpose, you can utilize [Denoify](https://denoify.land).

**Comment by sjdemartini** [comment]
@garronej I just wanted to say thank you again for your help in getting the above issues with building/packaging/publishing resolved. I've now published several early versions of my package https://github.com/sjdemartini/mui-tiptap which is using tss-react, and I'm using it in an external application, and it's been working great! Really appreciate you taking the time to provide guidance! 🙏

**Comment by garronej** [comment]
Thanks a lof for the feedback!  
tiptap looks great!
