### ISSUE TITLE
Reference all children jss to tss syntax

### ISSUE THREAD

**Issue by KellyP5** [garronej/tss-react#138]
Hello!,
In the migration process to mui v5. Previously used a lot of the below synax:
```javascript
"& > *" : { 
  ... reference all children css here
}
```
In migrating, I can't seem to figure out the syntax to accomplish the same thing with tss-react:

```javascript
export const useStyles = makeStyles()((theme) => ({
  row: {
    height: "50px",
    cursor: "pointer",
    "& > *": {
      paddingTop: 0,
      paddingBottom: 0,
      paddingRight: theme.spacing(1),
      paddingLeft: theme.spacing(1),
    },
    "&.Mui-selected": {
      backgroundColor: theme.colors.TEAL["1000"],
    },
    "&.Mui-selected:hover": {
      backgroundColor: theme.colors.TEAL["900"],
    },
  },
})
```

**Comment by garronej** [comment]
Hi @KellyP5,  
It works the same as in JSS.  
the codz you are sharing should work.

**Comment by KellyP5** [comment]
> Hi @KellyP5, It works the same as in JSS. the codz you are sharing should work.

Interesting, my guess is it is being overwritten by MUI theme then? Not sure why it is being ignored. I can adjust the setting in the primary theme or adjust the CSS on the components directly but haven't been able to get the above inheritance syntax to work

**Comment by garronej** [comment]
> my guess is it is being overwritten by MUI theme then?  

Pobably, inspect with the browser devloppement tools and see what's up...  

> Not sure why it is being ignored.  

Matchall selectors are very low specificity. Any other rule will overwrite them.  
You can abitratly increace specificity by adding extra `&` though.  
The more you add, the more specific your selector will get, example:  

```diff
export const useStyles = makeStyles()((theme) => ({
  row: {
    height: "50px",
    cursor: "pointer",
-    "& > *": {
+   "&&& > *": {
      paddingTop: 0,
      paddingBottom: 0,
      paddingRight: theme.spacing(1),
      paddingLeft: theme.spacing(1),
    },
    "&.Mui-selected": {
      backgroundColor: theme.colors.TEAL["1000"],
    },
    "&.Mui-selected:hover": {
      backgroundColor: theme.colors.TEAL["900"],
    },
  },
})
```

**Comment by KellyP5** [comment]
> 

This did the trick, thanks a lot @garronej
