### ISSUE TITLE
TS complains when using MUI sx prop syntax

### ISSUE THREAD

**Issue by mwskwong** [garronej/tss-react#139]
Directly copy and paste from the sample here will result in TS complaining about type mismatch
https://docs.tss-react.dev/mui-sx-syntax

![image](https://user-images.githubusercontent.com/32725014/213906553-d261aa63-5d0b-4e44-b7cd-2abaa5b9b32d.png)

**Comment by garronej** [comment]
Hi @mwskwong,  
Sorry about that, I'm looking into it.

**Comment by garronej** [comment]
I just updated the DOC.  
Type safety isn't great on this but it isn't great on the mui side either:  
<img width="708" alt="image" src="https://user-images.githubusercontent.com/6702424/213914559-6b5e8d0a-99ac-4758-97d7-008952633cda.png">  
and I think it's their responsability to improve this .  

Anyway, the example works now.   

Best regards
