### ISSUE TITLE
FOUC when upgrading MUI4 to MUI5 and using tss-react

### ISSUE THREAD

**Issue by sahanaravi** [garronej/tss-react#141]
I have a NextJS application and I upgraded from MUI4 to MUI5 and used tss-react and now I see a flash of unstyled content on page load. I see this issue in the MUI repo but they have resolution based on 'styled-components', but not specific to tss-react
The flickering is like this: https://github.com/vercel/next.js/issues/15642
I am unable to upgrade NextJS for now for specific reasons.

**Versions:**
"react": "17.0.2"
"next": "12.1.5"
"@mui/material": "^5.11.4",
"tss-react": "^4.5.2",

**_document.js**

```
MyDocument.getInitialProps = async(ctx) => {
    const originalRenderPage = ctx.renderPage
    const cache = createEmotionCache()
    const { extractCriticalToChunks } = createEmotionServer(cache)
    ctx.renderPage = () =>
        originalRenderPage({
            enhanceApp: (App) =>
                function EnhanceApp(props) {
                    return <App emotionCache={cache} {...props} />;
                }
            })

    const initialProps = await Document.getInitialProps(ctx)
      
    const emotionStyles = extractCriticalToChunks(initialProps.html)
    const emotionStyleTags = emotionStyles.styles.map((style) => (
        <style
            data-emotion={`${style.key} ${style.ids.join(' ')}`}
            key={style.key}

            // eslint-disable-next-line react/no-danger
            dangerouslySetInnerHTML={{ __html: style.css }}
        />
    ))

    return {
        ...initialProps,
        // Styles fragment is rendered after the app and page rendering finish.
        emotionStyleTags
    }
}

```
**AppWrapper.js**

 ```
<CacheProvider value={clientSideEmotionCache}>
                    <ConditionalWrapper
                        condition={theme}
                        wrapper={children => <ThemeProvider theme={theme}>{children}</ThemeProvider>}>
                            <SWRConfigProvider>
                                {children}
                            </SWRConfigProvider>
                    </ConditionalWrapper>
                </CacheProvider>

```
**App.js**
 ```
<React.Fragment>
                    <Head>
                        <meta name='viewport' content='minimum-scale=1, initial-scale=1, width=device-width'/>
                    </Head>
                    <AppWrapper pageProps={pageProps} theme={directionalTheme} locale={locale}>
                        <CssBaseline/>
                        <StateMachineProvider>
                            <GlobalStyles styles={globalStyles} />
                            <Header />
                            <CookiesProvider>
                                <Component {...pageProps} />
                            </CookiesProvider>
                        </StateMachineProvider>
                        <Footer/>
                    </AppWrapper>
                </React.Fragment>
```

**Comment by garronej** [comment]
Hello @sahanaravi,  

It's your lucky day, TSS provides helpers to setup SSR, just use that and everything should work fine.  
https://docs.tss-react.dev/ssr/next.js#single-emotion-cache  

I close because I assume it'll resolve your problem but feel free to reopen if you still have problems.

**Comment by sahanaravi** [comment]
Module not found: Can't resolve 'next/navigation' is the error I keep getting when I try that approach. Do we need any extra packages?

**Comment by garronej** [comment]
I

**Comment by garronej** [comment]
@sahanaravi It's fixed.  
If you update `tss-react` to `4.6.0` and import the utils with `import { createEmotionSsrAdvancedApproach } from "tss-react/next/pagesDir";` things should work.  

I've updated the doc: https://docs.tss-react.dev/ssr/next.js#single-emotion-cache

**Comment by sahanaravi** [comment]
Thank you for being so prompt in replying. My structure is like this. How would you incorporate augmentDocumentWithEmotionCache in here?
```
class MyDocument extends Document {
 
  render() {
 // Lots of other setup stuff here I cannot remove
    return (
      <Html>
        <Head />
        <body>
          <Main />
          <NextScript />
        </body>
      </Html>
    )
  }
}

// export default MyDocument
export default augmentDocumentWithEmotionCache(MyDocument) -- gives an error again--Error: The default export is not a React Component in page: "/_document"

```

**Comment by garronej** [comment]
You're wellcome :)  

Please read the documentation carefully, you're not supposed to export it like this.  

```diff
class MyDocument extends Document {
 
  render() {
 // Lots of other setup stuff here I cannot remove
    return (
      <Html>
        <Head />
        <body>
          <Main />
          <NextScript />
        </body>
      </Html>
    )
  }
}

-export default augmentDocumentWithEmotionCache(MyDocument)

+augmentDocumentWithEmotionCache(MyDocument)
+export default MyDocument;

```

**Comment by sahanaravi** [comment]
I will get the FOUC. Looks like SSR is not working with my packages. On Disabling Javascript, page is not rendered right after the upgrade. 
Packages I am using now

Versions:
"react": "17.0.2"
"next": "12.2.0"
"@mui/material": "^5.11.4",
"tss-react": "^4.6.0",
@emotion/react": "^11.10.5",
  "@emotion/server": "^11.10.0",
  "@emotion/styled": "^11.10.5",
  "@emotion/cache": "^11.10.5",

**Comment by garronej** [comment]
Sorry to hear that,  
You'll have to provide a reproduction repo if you want me to look into it.  
It should work.

**Comment by sahanaravi** [comment]
This was resolved. Somehow I realized the project was not supporting any non MUI elements like <div> or <a>. I replaced all of them with MUI elements <Box> , <Box component='a'> and it works.

**Comment by garronej** [comment]
Great, thank you for the feedback
