### ISSUE TITLE
SSR with NEXT js 12.1.5 does not work

### ISSUE THREAD

**Issue by sahanaravi** [garronej/tss-react#146]
I have a NextJS application and I migrated to MUI5 just recently. Things worked really well with tss-react but I saw some slowness in client side rendered pages. I put in the StyledEngineProvider and that fixed it, but having CacheProvider and StyledEngineProvider together brought an FOUC page on load and SSR seems to be broken. I followed instructions on https://docs.tss-react.dev/ssr/next.js#mui-and-tss-use-different-caches but it seems to require NextJS 12.1.7 or higher. They have some middleware changes I cannot do now, so is there a way I can may MUI5 Work well with NextJS 12.1.5 and tss-react in my application? I have implemented all code changes and the application comes up with no errors, just that SSR does not work still.

**Comment by sahanaravi** [comment]
Sorry it was my mistake.. It works fine

**Comment by garronej** [comment]
Does it? 
It's to my surprise. But allright.
