### ISSUE TITLE
Material UI classes argument and composition.

### ISSUE THREAD

**Issue by ProtonGustave** [garronej/tss-react#15]
Problem: i use composition as you proposed in docs, but there is a problem when i use it with `classes` props from MUI.
Let's i have styles object `tableRow`, i need it class name to use in composition, i'm doing `css(tableRow)` and it returns `tss-react-1yphcmd` i then use `classes.tableRow` in component code like this `classes={{ root: classes.tableRow }}`.
Then in browser i see this element has class `tss-react-1yphcmd-MuiTableRow-root`, i.e. something added `-MuiTableRow-root` string. What's the problem? I see easy workaround here but i really would prefer to simply use `css(tableRow)`.

**Comment by ProtonGustave** [comment]
I double checked, `tss-react-1yphcmd` suffix here is not same too.

**Comment by ProtonGustave** [comment]
So it looks like MUI compose styles and therefore there is another class. I see 2 problems with that:
1. old not used styles exists on page
2. can't do composition
Any thoughts?

**Comment by garronej** [comment]
Thanks for reporting, I will look into it latter today.

**Comment by garronej** [comment]
I am investingating the issue

**Comment by garronej** [comment]
I think I got it, let me release a new version

**Comment by garronej** [comment]
Sorry it took me so long to address this major issue.  
It's fixed in the latest version, if you configure your project as it is specified in the readme section for mui v5.

**Comment by ProtonGustave** [comment]
@garronej sorry for long response, thanks for effort, I'll test it soon.

**Comment by garronej** [comment]
Hi @ProtonGustave,  
Just a small notice to inform you that I updated the instructions on how to setup tss with mui yet again and I also made some small API changes.  
Sorry for the instability of the API. Everything will be freezed once mui v5 release.  
[See new instructions](https://github.com/garronej/tss-react#with-material-ui-v5)

**Comment by ProtonGustave** [comment]
@garronej looks like it works, thank you!
