### ISSUE TITLE
Broken UI for Select and Switch Material UI components in tss-react-v4

### ISSUE THREAD

**Issue by roman-zabolotskyi-axon** [garronej/tss-react#152]
`react-tss` upgrade from `3.7.1` to `4.6.1` caused broken UI for some of the `Material UI` components. `Switch` looks different in `checked` state and `Select` has lost its border.

* [Sandbox](https://codesandbox.io/s/tss-react-v3-nzq6tt) for `react-tss 3.7.1`
* [Sandbox](https://codesandbox.io/s/tss-react-v4-sd38u1) for `react-tss 4.6.1`

As you can see in `4.6.1` styles aren't applied like in `3.7.1`, but the code is identical.

**Comment by garronej** [comment]
Yes sorry about that,  
There is an ongoing PR on the MUI repo that fixes that.  
https://github.com/mui/material-ui/pull/34659  

In the meantime you can easyly fix this by using diffrent caches:  
https://docs.tss-react.dev/troubleshoot-migration-to-muiv5-with-tss

Fixet sandbox: https://codesandbox.io/s/tss-react-v4-forked-o5uu91

**Comment by roman-zabolotskyi-axon** [comment]
Thanks for the quick response. Your solution works for `Select/Switch` components, but there are other issues. Let me add a bit of context.

We have an application running `React 17/Material UI/emotion (with style caching)/tss-react v3` and want to upgrade to `React 18`. Package update of `react/react-dom` caused issues, one of them related to incorrect order of global styles. After some digging I found about 10 different issues on `emotion` library [like this](https://github.com/emotion-js/emotion/issues/2803). Possible solutions that didn't help:

* tweak `emotion` cache settings
* use `TssCacheProvider`
* use `TssCacheProvider` together with `CacheProvider`
* remove all CSS cache

The only thing that made the CSS order to be correct with `React 18` is an upgrade of `tss-react` to `v4`. But it caused broken UI for `Select/Switch`. While your solution helps to fix the problem it turns us back to the wrong CSS order. So, at the moment we're stuck in either one of two states:

* wrong `CSS` order + correct rendering of `Select/Switch`
* correct `CSS` order + wrong rendering of `Select/Switch`

It seems we should wait for the MUI PR to get merged. Do I get it right?

**Comment by garronej** [comment]
@roman-zabolotskyi-axon,  

Yes you can of course fix the style at the component level.  
Just use && to artifitially increase specificity so that your custom style overwrite MUI's.  

https://codesandbox.io/s/tss-react-v4-forked-nnfx68

**Comment by roman-zabolotskyi-axon** [comment]
Style specificity fixed the UI. Thanks a lot!
