### ISSUE TITLE
Modern code in npm

### ISSUE THREAD

**Issue by Semigradsky** [garronej/tss-react#155]
It looks like `tss-react` now has modern code in npm so need to bundle it before use.
Early (v4.4.4) it was more usable for browsers code. Is it change really needed?

**Comment by garronej** [comment]
Hi @Semigradsky,  

TSS has distribution for both ESM and CJS.  
![sainte grace de dieux](https://user-images.githubusercontent.com/6702424/223423650-a16d9364-e5ed-4aeb-8309-062633e7afdf.png)  

Do you want me to change the target to ES5: https://github.com/garronej/tss-react/blob/71b5dbd0bef470dac100f1eaf03afce7ea72990b/tsconfig.json#L4  

I see no problem with that...

**Comment by garronej** [comment]
What target do you think is best:  

For ESM? ES6, ES2020?
For CJS? ES5, ES3?  

I'm curious to have your idea.  
My resoning is that older target make the file bigger hence increacing the bundlesize.

**Comment by Semigradsky** [comment]
It is `ES2020` as I see.
https://github.com/garronej/tss-react/blob/71b5dbd0bef470dac100f1eaf03afce7ea72990b/tsconfig-esm.json#L5
`ES6` is okay for me.

**Comment by garronej** [comment]
you can submit a PR for:  
https://github.com/garronej/tss-react/blob/71b5dbd0bef470dac100f1eaf03afce7ea72990b/tsconfig-esm.json#L5  
https://github.com/garronej/tss-react/blob/71b5dbd0bef470dac100f1eaf03afce7ea72990b/tsconfig.json#L4  

I'm always happy to have a new contributor

**Comment by Semigradsky** [comment]
Blazy fast! 👍
