### ISSUE TITLE
Issue with assigning passing in props for custom classes prop

### ISSUE THREAD

**Issue by jrothweiler** [garronej/tss-react#158]
This issue looks kind of similar to #128 (same general TS error at least) but wasn't certain so I am making its own issue.

I am looking to upgrade an MUI-based component library with this library to continue using JSS. Our components provide their own `classes` interface which we merge in so that feature of tss-react was great to see.

The feature works fine for merging in class names though it isn't very flexible with type checking what you pass in. I have a minimal reproduction component that shows roughly what we do:

```
export const useStyles = makeStyles({ name: 'TestComponent' })(() => ({
  root: {
    height: '100px',
  },
  text: {
    color: 'red',
    '&:hover': {
      color: 'green'
    },
  },
}))

export interface TestComponentProps {
  foo?: string
  bar?: string
  baz?: string
  classes?: {
    root?: string
    text?: string
  }
}

const TestComponent = (props: TestComponentProps) => {
  const { classes } = useStyles(undefined, { props }) // this line is the problem

  return (
    <div className={classes.root}>
       <Typography className={classes.text}>This is a test</Typography>
    </div>
  )
}

```

Passing in the full `props` object results in the following TS error:

```
Type 'TestComponentProps' is not assignable to type '{ classes?: Record<string, string> | undefined; } & Record<string, unknown>'.
  Type 'TestComponentProps' is not assignable to type 'Record<string, unknown>'.
    Index signature for type 'string' is missing in type 'TestComponentProps'.ts(2322)
```

As noted in the docs there is an easy workaround to just not pass in the whole object, like `useStyles(undefined, { props: { classes: props.classes } })` . But it feels like we should be able to do the above code without needing to specify that our props interface is a dictionary.

**Comment by garronej** [comment]
Hello @jrothweiler,  
Thanks for the report, Indeed, it shouldn't give you an error here.    

If you convert `TestComponentProps` into a `type` instead of an `interface` it will work.   

I can find a type (other than `any`) for this param that would make it work:  
- when using `type` and there is a `classes` prop. 
- when using `type` and there is no `classes` prop.
- when using `interface` and there is a `classes` prop.
- when using `interface` and there is no `classes` prop.  

There is always one that gives red.

**Comment by garronej** [comment]
Yes but if pepole want to write component that can be globaly overwriten (MUI) we need to pass all props...  
I'm thinking about making it `any`...  
I think in this case type safety does more harm than good, you shouldn't be worried about this.

**Comment by garronej** [comment]
Error should be gone in the latest version
