### ISSUE TITLE
withStyles

### ISSUE THREAD

**Issue by garronej** [garronej/tss-react#16]
Could you implement `withStyles` in `tss-react` too? It's convenient when just want to overwrite the style of a Mui Component.

```ts
const StyledLinearProgress = withStyles(LinearProgress)({
    root: {},
    // other LinearProgressProps.classes properties...
})
```

_Originally posted by @Jack-Works in https://github.com/mui-org/material-ui/issues/26571#issuecomment-903371766_

**Comment by garronej** [comment]
Hi @Jack-Works,
I have started to implement it but it turned out not to be as trivial as I though it would be.  
1) I gess we want to levrage mui's [`classes` prop](https://material-ui.com/customization/components/#overriding-styles-with-classes) but there's [an issue](https://github.com/garronej/tss-react/issues/15) that have been open about it that I should adress first.  
2) I can't implement the API [as in mui](https://material-ui.com/styles/basics/#higher-order-component-api) because if the style object is provided first the type of `props` argument can't be inferred.  

I will work on theses points, feel free to give feedback on the branch I just created.

**Comment by Jack-Works** [comment]
> I can't implement the API as in mui because if the style object is provided first the type of props argument can't be inferred.

I'm only focused on extending the existing components with `classes` props. In this case it;s easy to infer the types. Can you give an example of what are you considering?

```ts
function createMakeStyles<Theme>(useTheme) {
    function withStyles<T>(Component: React.ComponentType<T>) {
        type Classes = T extends { classes?: Partial<Record<infer U, string>> } ? U : never
        return function appendStyles(style: StyleOf<Classes, T>) {}
    }
}
```

**Comment by garronej** [comment]
[This is](https://github.com/garronej/tss-react/blob/feat_withStyles/src/withStyles.tsx) where I am at so far. I will do another overload to leverage the mui `classes` prop.  
I think our `withStyles` can just be a function that takes two arguments, the Component and the css rather than a higher-order function.  
[In mui](https://material-ui.com/styles/basics/#higher-order-component-api) they do first the css then the component but it can't be typesafe in this order.  
You propose to provide the component first then the css. Which works type-wise but do you see a use case that would justify it to be a higher-order function rather than just a function with two parameters?

**Comment by Jack-Works** [comment]
> You propose to provide the component first then the css. Which works type-wise but do you see a use case that would justify it to be a higher-order function rather than just a function with two parameters?

I guess it can be a single function. It just looks like a `styled` to me. `styled(Component)(style)`

**Comment by Jack-Works** [comment]
https://github.com/garronej/tss-react/blob/0e0dd95ef2660b8f8b0690ec0ba1ef50ded7954c/src/withStyles.tsx#L30

You should use `forwardRef` to make sure ref is forwarded

**Comment by garronej** [comment]
Ok, now that I have addressed the problem related to the mui `classes` props I will be abe to work on this.  

By the way, the only way I found to make `tss-react` work flawlessly with mui v5 is to make material-ui and tss-react use a different cache. 

![image](https://user-images.githubusercontent.com/6702424/131266858-44b36d5b-b1fd-4a54-a990-98b32979785a.png)

When the cache is explicitly provided to `createMakeStyle` the contextual cache is no longer picked up. Is this something that could be troublesome in your case?

**Comment by Jack-Works** [comment]
> When the cache is explicitly provided to createMakeStyle the contextual cache is no longer picked up. Is this something that could be troublesome in your case?

If `tss-react` can use the emotion cache I provided, it is OK.

**Comment by Jack-Works** [comment]
> When the cache is explicitly provided to createMakeStyle the contextual cache is no longer picked up. Is this something that could be troublesome in your case?

The contextual cache is important in our use case. Is there some features that cannot work with contextual cache? (We're not using SSR)

**Comment by garronej** [comment]
Mui v5 `classes` prop cannot work if `tss-react` and mui uses the same emotion cache.  Or rather it work but the style don't have priority so most often than not it will be overwriten by mui's default style unless you put `! important`.  
This is due to an optimisation that MUI does internally.  The only way I found to bypass de problem is to make `tss-react` use a different cache.  
If it's a problem for you I can try to work this out with the mui's team.

**Comment by Jack-Works** [comment]
> This is due to an optimisation that MUI does internally. The only way I found to bypass de problem is to make tss-react use a different cache.

Hi, it's OK to have a different cache for MUI and tss-react for us, but the cache must come from the React Context. e.g. We can write this:

```jsx
<MuiEmotionCacheProvider cache={cache1}>
    <TSSReactEmotionCacaheProvider cache={cache2}>
        {children}
```

**Comment by garronej** [comment]
This is a can do, IDK why I didn't think of it myself. Let me implement that.

**Comment by garronej** [comment]
@Jack-Works I implemented [the cache provider you suggested](https://github.com/garronej/tss-react#cache).  
I hope it fits your needs.

**Comment by Jack-Works** [comment]
> @Jack-Works I implemented [the cache provider you suggested](https://github.com/garronej/tss-react#cache).
> I hope it fits your needs.

Yes, it works in our product. Thanks for your work!

**Comment by Jack-Works** [comment]
I have upgraded to the latest version in https://github.com/DimensionDev/Maskbook/pull/4163

**Comment by LabuzzMichal** [comment]
Hi, any update regarding withStyles ?:)

**Comment by garronej** [comment]
not yet,  but I hope I'll find the time to finalize it by Monday.

**Comment by garronej** [comment]
Ok I think I got it to work.  
I hope I will be able to release it tonight. I need to test carefully.

**Comment by garronej** [comment]
@LabuzzMichal, sorry. I have worked extensively on this this week end but it still needs some more work before being released.

**Comment by LabuzzMichal** [comment]
@garronej thank you for update!
Take your time, you already did excellent job with makeStyles :)
I believe once its done your library will gather much more attention since upgrade from MUI 4 to MUI 5 will be much easier

**Comment by garronej** [comment]
Just a quick update to notify that I am working on this

**Comment by garronej** [comment]
[I pull it off eventually](https://github.com/garronej/tss-react/blob/3f20a6715f28bfaf8b9e8ddc0664d59c84b159e0/src/test/apps/spa/src/App.tsx#L245-L273) 🎉  
It was extremely challenging to get the type inference right.  
I will need an extra session to redact the documentation and to some more advanced testing.  
Maybe it would be cool as well if it was possible to write:  
```typescript
const MyDivStyled= withStyle("div", { "root": { "color": "red" } });
```
Anyway it's available on the latest patch update. I will do a minor bump when everything is tested and documented.

**Comment by LabuzzMichal** [comment]
Great, thank you :)
Will check it tomorrow

**Comment by garronej** [comment]
@LabuzzMichal thank you for the feedback.

[It's all documented and tested](https://github.com/garronej/tss-react#withstyles)
