### ISSUE TITLE
MUI styles overriding Tss react styles while upgrading to MUI v5

### ISSUE THREAD

**Issue by vengeance1464** [garronej/tss-react#169]
I have tried using tss react cache and mui cache and still MUI styles are overriding the TSS react styles.
I have tried uninstalling mui packages ,removing package-lock.json still the issue is not getting solved.
I have to  increase specificity of tss styles.
Please help

**Comment by garronej** [comment]
Hello,

Please share a reproduction repository

**Comment by Priyam1464** [comment]
Its a private repository

**Comment by garronej** [comment]
The issue you're encountering often arises when multiple instances of `@emotion/react` coexist within your application. This is also a common problem in microfrontend projects, where there might be a single copy of `@emotion/react`, but multiple instances of the code are running simultaneously, resulting in the same issue.

> This is a private repository

Please note, a reproduction repository doesn't have to be the original repository itself. Instead, it can be a minimal repository that allows the library maintainer to replicate and understand the problem.

**Comment by vengeance1464** [comment]
There are a lot of files so I have just added few files to show how I am using tss reactin project.I have given access to  this repo to you @garronej 
https://github.com/vengeance1464/test-mui

**Comment by garronej** [comment]
Well @vengeance1464,  
I don't know specifically what isn't working as you expect it to and I can't run the repo you shared.  

All I can see is you are still using `clsx`, with `tss-react` you are supposed to use `cx()` instead.  
<img width="756" alt="image" src="https://github.com/garronej/tss-react/assets/6702424/61d165ef-2962-424d-9c3c-dade9155daca">

Also here: https://github.com/vengeance1464/test-mui/blob/4149f752773e52c226794cc88a4c941350236317/text-field-styles.ts#L5  
You are explicitely labeling the `theme` argument with `Theme`. This is not required. The type is iffered automatically. Not that it has any effect on your problem though.

**Comment by vengeance1464** [comment]
For eg  here mui style is overriding tss react style
![image](https://github.com/garronej/tss-react/assets/20543398/13fd210e-a6b9-4337-a5fc-d0d8e8da9e81)

**Comment by garronej** [comment]
Styles created by Emotion typically follow the format `.<cache name>-<hash>-...`. However, the styles you've shown me are applied directly to `.MuiInputBase-input`. Please note that these styles are not handled by Emotion, hence it's your responsibility to appropriately position them in the `<head>` section of your document. 

Unfortunately, without seeing the context or the code, it's challenging for me to determine how you've ended up in this situation. If you could provide me with your code, I would be able to quickly identify and explain the issue at hand.

**Comment by vengeance1464** [comment]
There is no head section in the code.This .MuiInputBase-input is being applied to TextField by default in the TextFieldComponent.tsx in the repo at line 368. However earlier the jss styles were overriding these but not in tss.
**Previous Behaviour**
<img width="959" alt="image" src="https://github.com/garronej/tss-react/assets/20543398/7544e336-c579-47c8-a969-30dd3de22f29">
**New Behaviour**
<img width="877" alt="image" src="https://github.com/garronej/tss-react/assets/20543398/50f66108-1d0d-4a3c-8003-84ac8b7d97ff">
<img width="353" alt="image" src="https://github.com/garronej/tss-react/assets/20543398/d5ba4a69-ea63-47fe-a8ba-898c296d78e6">
<img width="455" alt="image" src="https://github.com/garronej/tss-react/assets/20543398/095eb3d2-93eb-4ecc-910e-75bf860c84e4">

**Comment by garronej** [comment]
The builtin MUI styles are usually applied through @emotion. This is why TSS is able to control the priority.  

![image](https://github.com/garronej/tss-react/assets/6702424/f9b61a4f-362c-4e72-9686-35294cd84bc7)

Do you have the production link of the website that uses JSS?

**Comment by vengeance1464** [comment]
I am not allowed to share the link, but I found the issue that while using jss we were using something like this example
<img width="356" alt="image" src="https://github.com/garronej/tss-react/assets/20543398/9190857b-3efd-415e-8316-aad0a2c853d7">


we were adding {index:1} to change CSS injection order and because of this they were overriding the mui styles but I couldnt find the equivalent of {index:1} in tss react

**Comment by garronej** [comment]
> I am not allowed to share the link  

While I understand you're unable to share the project's code, it would be highly beneficial if you could create a separate repository that reproduces the issue you're facing. This is a common strategy when seeking help from maintainers.  
If this is not possible for you, I regret to inform you that this will be my final response.  

There are two primary methods for controlling priority in Emotion:  
- Utilizing [cx](https://emotion.sh/docs/@emotion/css#cx) (returned by `useStyles`). This method can prove helpful, especially given that for unknown reasons, the default MUI styles don't seem to apply by Emotion in your project.  
- Establishing a custom emotion cache allows you to specify an `insertionPoint`, which dictates where your style should be inserted within the head. Ideally, you'd want your custom styles to be placed after Mui's default style in the head.
