### ISSUE TITLE
Add an example based on the material-ui nextjs example

### ISSUE THREAD

**Issue by janus-reith** [garronej/tss-react#18]
I would like to see an example how to integrate tss-react based on this: https://github.com/mui-org/material-ui/tree/next/examples/nextjs-with-typescript

The current way things work is a bit confusing to me:
The example in the MUI docs has a shared util `createEmotionCache` which when called, always returns the result of emotions `createCache` function.

Now both _app and _document call that, _document uses it once in initial props, _app stores it global to the file.

The example here acts in a different way: The `createDocument`  function returns getInitialProps logic, which internally uses `getCache`.
There is no _app, but I assume looking at what index.tsx does is the same what _app would do per page. index.tsx also uses the same `getCache` function.
What `getCache` basically does, is it stores a `cache` globally, and returns in or if it doesn't exist yet, create it using `createCache` from emotion.
That seems to be different from what the mui example does, since _document and _app receieve their own instance here.

Some more background to why this example would help understanding the cache utilization is in https://github.com/garronej/tss-react/issues/19.

Having an example using the same structure as the MUI one would help a lot to understand the differences there.

**Comment by garronej** [comment]
https://github.com/garronej/tss-react/tree/main/src/test/ssr
