### ISSUE TITLE
Use eslint rule to detect unused classed with imports

### ISSUE THREAD

**Issue by michielmetcake** [garronej/tss-react#187]
We'd like to use https://docs.tss-react.dev/detecting-unused-classes in our project where we use `tss-react`.

When adding the eslint rule all our classes are marked as `unused` by the plugin because we use import the  like this:

```
import { useStyles } from './Component.style';
```

```
const Component = () => {
   const { classes } = useStyles();
   
   return (<div className={classes.container}>styled div </div>)
}
```

Is there currently a way to support this usage?

**Comment by garronej** [comment]
Hello @michielmetcake,  

I'm sorry but, no the plugin isn't smart enough for this 😕

**Comment by michielmetcake** [comment]
> Hello @michielmetcake,
> 
> I'm sorry but, no the plugin isn't smart enough for this 😕

I appreciate your reply. Thank you!
