### ISSUE TITLE
TssCacheProvider is not working when used with emotion cache and mui 5

### ISSUE THREAD

**Issue by bilalajanjua** [garronej/tss-react#201]
Hi, thanks for the cool library.

We have our design system upgraded from mui v4 to mui v5 and we are planning to use tss-react instead of using new styling system by mui 5. We have transformed our style files to use `makeStyles` from `tss-react/mui` but it is causing specificity problems. i.e. the default overrides take more precedence over custom styles. 

We have tried following the instructions mentioned here: https://docs.tss-react.dev/troubleshoot-migration-to-muiv5-with-tss
But it didn't work. Somehow TssCacheProvider is not taken into account and only the emotion cache is used.

If we use `createMakeAndWithStyles` then it works fine but we would like to use provider approach instead of exporting our own `makeStyles` helpers. 

Our style app wrapper looks something like this.

```jsx
import createCache from "@emotion/cache";
import { CacheProvider } from "@emotion/react";
import { ThemeProvider } from "@mui/material";
import PropTypes from "prop-types";
import { useSelector } from "react-redux";
import { prefixer } from "stylis";
import rtlPlugin from "stylis-plugin-rtl";
import { TssCacheProvider } from "tss-react";

const appName = "ds";

const getInsertionPoint = () => {
  const insertionPointName = `${appName}-styles-insertion-point`;

  const node = document.querySelector(`#${insertionPointName}`);
  if (node) {
    return node;
  }
  const newNode = document.createElement("style");
  newNode.setAttribute("id", insertionPointName);
  document.head.appendChild(newNode);
  return newNode;
};

const ltrCache = createCache({
  key: `${appName}-ltr`.toLowerCase(),
  prepend: true,
  insertionPoint: getInsertionPoint(),
});

const rtlCache = createCache({
  key: `${appName}-rtl`.toLowerCase(),
  prepend: true,
  stylisPlugins: [prefixer, rtlPlugin],
  insertionPoint: getInsertionPoint(),
});

function StyleApp({ children }) {
  const theme = useSelector((state) => state.theme);
  const direction = useSelector((state) => state.appSettings.direction);

  return (
    <ThemeProvider theme={theme}>
      <CacheProvider value={direction === "rtl" ? rtlCache : ltrCache}>
        <TssCacheProvider
          value={createCache({
            key: `${appName}-tss`.toLowerCase(),
          })}
        >
          {children}
        </TssCacheProvider>
      </CacheProvider>
    </ThemeProvider>
  );
}

export default StyleApp;

```

Even if we don't use custom insertion point, provider still doesn't work. 
Thanks in advance for looking into this issue.

**Comment by garronej** [comment]
Hi @bilalajanjua,  

Your setup looks good and very standard to me, it should work, hundreds of project use tss-react in this extact same way for the exact same usecase.  
But don't worry we're going to troubleshoot.  
Usually, when the cache is not picked up it mean that you're facing a dual package situation where, `<TssCacheProvider />` and `makeStyles` does not comes from the same copy of `tss-react`.  
Looking at you code, maybe you are in a situation where you have a ui module and a main app. (Like we have with Onyxia: [the main app](https://github.com/InseeFrLab/onyxia) and [the ui toolkit](https://github.com/InseeFrLab/onyxia-ui)). If that is the case, the problem likely steam from the way you are packaging your UI module.  

Maybe you can have a look at this:  
https://docs.tss-react.dev/publish-a-module-that-uses-tss  

Let me know if it works.

**Comment by bilalajanjua** [comment]
Hi @garronej,

Thanks for the reply.

I have verified that we only have one copy of `tss-react` installed. 

![image](https://github.com/garronej/tss-react/assets/11469682/19e96ff5-5d2f-45cf-9e51-146e9502a133)

Furthermore, I am trying to test the styles in storybook of the same design system repository. So It should be using the same single copy of `tss-react`. 

To give more info, here's how it is generating class names now:

<img width="503" alt="image" src="https://github.com/garronej/tss-react/assets/11469682/d3a19243-3b9d-46d9-830c-6a12b3683586">

And if I use `createMakeAndWithStyles` and export `makeStyles` from there, then it generates classes like this:

<img width="498" alt="image" src="https://github.com/garronej/tss-react/assets/11469682/91900c06-7bd5-446f-9aa6-847fffd817f1">

I have also checked other libraries: `@mui/material`, `@emotion/cache`, `@emotion/react` and they also have one single copy.

**Comment by garronej** [comment]
Then it probably means that, for some reason, some part of your App is loading the ESM distribution of tss-react while the other is using the CJS distibution.  
This would be the only remaining explanation as to why the cache might not be picked up.  
What bundler are you using?  
If you provide me with a reproduction repo I can address it.

**Comment by bilalajanjua** [comment]
Hi @garronej,

Thanks for the indication.

I have added logs inside the bundled esm version of `tss-react/esm` to see if the Provider is picked up from that file and it turned out that the bundler was importing the provider from the `esm` folder while the `tss-react/mui` was somehow picked up directly from `tss-react` root directory (i.e. cjs bundle). 

I don't know why this is happening but i have fixed this issue by pointing it manually via webpack config like this:

```json
{
    "resolve": {
        "alias": {
            "tss-react/mui": resolve(__dirname, "node_modules/tss-react/esm/mui"),
        }
    }
}
```

To answer your question:

We are using webpack v4 for the storybook. But to bundle our library we are using Vite. We would keep using the above mentioned solution for now as we are already planning to migrate to Vite for storybook as well.

Thanks again for the help and building such a cool library :)

**Comment by garronej** [comment]
@bilalajanjua,  
Thanks a lot for taking the time to share your workaround on this.  
Trust me I did my absolute best to get tss-react to work in every configuration with every bundle but the state of the javascript ecosystem is just a mess with CJS/ESM that can't interoperate.  

I had to publish in ESM + CJS because of [a bug in Vite](https://github.com/vitejs/vite/pull/13370) that has since been resolved.  
No I guess I could publish only in CJS but it would break things for project using older Vite version. It's a nightmare.

**Comment by bilalajanjua** [comment]
Hi @garronej, 

I understand that with many bundler options, it is sometimes hard to find one fix for all. This ESM + CJS is pretty standard and the package also has `exports` field in package.json which is understood by most bundlers. I think this problem occurs only with Webpack 4 (https://github.com/webpack/webpack/issues/9509) as it does not respect `exports` field of package.json, so maybe just documenting this workaround somewhere would be sufficient?
