### ISSUE TITLE
Using `@import` rule within `<GlobalStyles />` component

### ISSUE THREAD

**Issue by Razinsky** [garronej/tss-react#207]
Hello! I've been trying to create an `@import` rule to import font faces with the `<GlobalStyles />` component without success. I did some research on the issues and on the Web, but I could not find anything.

I tried many approaches:
```
// Doesn't work
<GlobalStyles
  styles={{
    import: `@import url("${typography.fontFace.import}")`,
  }}
/>
```
```
// Doesn't work
<GlobalStyles
  styles={{
    import: `url("${typography.fontFace.import}")`,
  }}
/>
```
```
// Doesn't work
<GlobalStyles
  styles={{
    import: typography.fontFace.import,
  }}
/>
```
```
// Doesn't work
<GlobalStyles
  styles={{
    "@import": `url("${typography.fontFace.import}")`,
  }}
/>
```
```
// Doesn't work
<GlobalStyles
  styles={{
    "@import": typography.fontFace.import,
  }}
/>
```

I feel like I've exhausted my options here 😓 Any help would be much appreciated. Thank you 🙏

**Comment by Razinsky** [comment]
UPDATE: I was able to make it work using string interpolation instead of CSS object:

```
// Does work ✅
<GlobalStyles
  styles={`
    @import url(${typography.fontFace.import});
  `}
/>
```

**Comment by garronej** [comment]
Fantastic thanks for reporting. Maybe it would be worth mentioning in the doc.  
https://github.com/garronej/tss-react/blob/v4_docs/api/globalstyles.md

**Comment by garronej** [comment]
I just updated the doc!  
Thanks for taking the time to report your solution!  

https://docs.tss-react.dev/api/globalstyles  

How's your experience with TSS other than that? In what context are you using it?

**Comment by Razinsky** [comment]
Amazing 🙌 .

Our experience so far is good. We just completed a full migration from MUI/JSS to TSS. So far, we see performance gains so we are happy :)

**Comment by garronej** [comment]
Great to hear,  
And are you using the modern API or `makeStyles()()`?

**Comment by garronej** [comment]
Great to know thanks!  

if the url of your app is public don't hesitate to share!

**Comment by Razinsky** [comment]
Also, my team gave me a much better solution for this using the `Array` if you want to include as well in the docs: 
```
// Does work ✅
<GlobalStyles
  styles={[
    `@import url(${typography.fontFace.import});`,
    {...cssObject}
  ]}
/>
```
