### ISSUE TITLE
Cannot read properties of undefined (reading 'length') in useGuaranteedMemo

### ISSUE THREAD

**Issue by antonmikhaliou** [garronej/tss-react#209]
Hey, ran into a problem when writing tests where makeStyles is used in a child component. The ref.current.prevDeps.length in the useGuaranteedMemo. If I use ref.current.prevDeps?.length as a check for undefined, everything works fine. Could you please add a check? You would be very helpful. Thanks in advance.

**Comment by antonmikhaliou** [comment]
Great, when will you be able to update?

**Comment by garronej** [comment]
I'm having trouble understanding how you're encountering this error. I'd greatly appreciate a detailed reproduction path, as there may be an aspect of useRef's functionality that I've overlooked. If this is the case, the TypeScript types of `useRef` aren't actuate.  
Are you working within a Next.js App router project by any chance?  
Regardless, I believe the issue should have been resolved in the latest release of tss. Please do inform me if the problem persists.

Best regards,
