### ISSUE TITLE
Prop `className` did not match.

### ISSUE THREAD

**Issue by nphmuller** [garronej/tss-react#212]
When migrating a create-react-app project to Next I stumbled upon the following error during hydration. Maybe I'm doing something wrong, but I think it might be a bug in tss-react. After a lot of tinkering I managed to make the following minimal repro. It's a little bit contrived, to make it as small as possible.

You can reproduce it the following way:

> git clone https://github.com/nphmuller/tss-react-classmatch-issue.git
> cd tss-react-classmatch-issue
> npm i
> npm run dev

Now when opening the page in the browser the following error gets logged:

> Warning: Prop `className` did not match. Server: "mui-ek3luc-icon mui-1-icon-ref" Client: "mui-ek3luc-icon mui-0-icon-ref"

**Some details on how I got the error**

- In page.tsx we render the following:
``` tsx
    <>
      <OtherComponentThatCallsMakeStyles />
      <ComponentWithIssue />
    </>
```

- The 1st component just calls makeStyles() and renders nothing. It doesn't matter what it renders, just that makeStyles() is called before the component with the issue.
- The main issue lies in the 2nd components, which contains the following code:

``` tsx
const useStyles = makeStyles<void, "link" | "icon">()(
  (_theme, _props, classes) => ({
    link: {
      // Removing this fixes the issue
      [`& .${classes.icon}`]: {
        color: "blue",
      },
    },
    icon: {},
  })
);

const ComponentWithIssue = () => {
  const { classes } = useStyles();

  return (
    <a className={classes.link}>
      <span className={classes.icon}>Icon</span>
    </a>
  );
};
```
The ``[`& .${classes.icon}`]:`` clause seems to cause the different classname to be generated server-side vs client-side.

**Additional details**

```
> node -v
v20.9.0
```

``` json
    "@emotion/styled": "11.11.5",
    "@mui/material": "5.15.15",
    "@mui/material-nextjs": "5.15.11",
    "next": "14.2.3",
    "react": "^18",
    "react-dom": "^18",
    "tss-react": "4.9.6"
```

Mui was setup the following way (via layout.tsx):

``` tsx
import { ThemeProvider, createTheme } from "@mui/material/styles";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";

...

  <AppRouterCacheProvider>
    <ThemeProvider theme={createTheme()}>{children}</ThemeProvider>
  </AppRouterCacheProvider>
```

**Comment by garronej** [comment]
Ok it's a confirmed bug, thanks for reporting and taking the time to setup a repro repo. That's refreshing.  

I'm on it. I can already see that my past self left a message about this for present me:  

![image](https://github.com/garronej/tss-react/assets/6702424/5db8078f-b808-48df-8975-e97ff8932068)

**Comment by nphmuller** [comment]
Thank you so much for the lightning fast response. I should have suspected it was a usage error. It usually is 😁.

I'll make the necessary changes and I'll close this issue now.

Thanks again!

**Comment by garronej** [comment]
@nphmuller,  

No, no! You did good opening this issue, as I said revisiting the code made me found another bug!  
Beside, the documentation about this wasn't clear enough.

**Comment by garronej** [comment]
Hello @ArtemAstakhov,  

Sorry I can't reproduce.  
I created a reproduction repo with your code. No issue

https://github.com/garronej/tss-react/assets/6702424/aa5c081a-76d1-45f9-b9d9-6af9bfe710c7

Can you please try do fork and modify the repo to make the issue your experiencing appear:  

https://github.com/garronej/tss-issue-212  

If I can reproduce I will adress it switfly.

**Comment by garronej** [comment]
@ArtemAstakhov Great! Thank you for the update!
