### ISSUE TITLE
"this" has been rewritten to "undefined" warning during the Rollup build (ESM)

### ISSUE THREAD

**Issue by cjnoname** [garronej/tss-react#216]
Hi,

We encountered an issue where tss-react gives me a warning during the ESM build with Rollup.

Here is the detail of the warning:

(!) "this" has been rewritten to "undefined"
https://rollupjs.org/troubleshooting/#error-this-is-undefined
node_modules/tss-react/esm/tss.js
1: /* eslint-disable @typescript-eslint/ban-types */
2: var __rest = (this && this.__rest) || function (s, e) {
                 ^
3:     var t = {};
4:     for (var p in s) if (Object.prototype.hasOwnProperty.call(s, p) && e.indexOf(p) < 0)
...and 1 other occurrence
node_modules/tss-react/esm/withStyles.js
1: var __rest = (this && this.__rest) || function (s, e) {
                 ^
2:     var t = {};
3:     for (var p in s) if (Object.prototype.hasOwnProperty.call(s, p) && e.indexOf(p) < 0)

The link below serves as a reference for this error:
https://rollupjs.org/troubleshooting/#error-this-is-undefined

**Comment by cjnoname** [comment]
Also below with the same issue:

node_modules/tss-react/esm/withStyles.js
1: var __rest = (this && this.__rest) || function (s, e) {
                 ^
2:     var t = {};
3:     for (var p in s) if (Object.prototype.hasOwnProperty.call(s, p) && e.indexOf(p) < 0)

**Comment by garronej** [comment]
Hello, thanks for reporting. Do you experience any bug besides this warning?

**Comment by cjnoname** [comment]
> Hello, thanks for reporting. Do you experience any bug besides this warning?

Not sure mate, we haven't tried, but this is the only warning we had during the build

**Comment by cjnoname** [comment]
> Well, this warning sucks because this is perfectly valid code. Anyway I changed the compilation target for the ESM distribution in tss-react@4.9.12.
> 
> Thanks for reporting

Thanks for your quick fix mate
