### ISSUE TITLE
TypeError: (0 , cache_1.default) is not a function

### ISSUE THREAD

**Issue by lucacampana-whs** [garronej/tss-react#22]
Good day, I'm trying to test a component that makes use of tss (I'm migrating from the materialUI v4 `makeStyles`), while this is working fine during development, I'm encountering an issue when trying to test a component that makes use of tss

The error is the following:
```ts
    TypeError: (0 , cache_1.default) is not a function

      12 |
      13 | export const DummyElement = () => {
    > 14 |   const { classes, cx } = useStyles();
         |                           ^
      15 |   return <div className={cx(classes.root)}>DUMMY</div>;
      16 | };
      17 |
```

This is with material UI v5, I followed all the steps in the readme, I created a minimal reproducible example in this repository: https://github.com/lucacampana-whs/tss-react-issue-jest-cache

**Comment by garronej** [comment]
Thank you for taking the time to make a reproductible example.  
I will have a look at it first time tomorrow.

**Comment by garronej** [comment]
For some reason, in your setup it won't import `@emotion/cache` I'll keep investigating

**Comment by garronej** [comment]
It's fixed, sorry I took me so long.

**Comment by lucacampana-whs** [comment]
@garronej No worries, thanks a lot for the support!
