### ISSUE TITLE
Typing problem when using a custom theme with MUI v6

### ISSUE THREAD

**Issue by Canuckaholic** [garronej/tss-react#221]
I'm trying to upgrade our project to use MUI v6. We use a custom theme:
```
declare module "@mui/material/styles" {
  interface Theme {
    constants?: ThemeConstants;
  }
}
```
However, where we use `tss.create` the theme object doesn't include our custom properties:
```
export const useStyles = tss.create(({ theme }) => ({
  root: {
    border: "1px solid transparent",
    borderRadius: theme.constants?.roundedButtonRadius,
    maxWidth: "calc(100vw - 64px)",
}))}
```

In that example above Typescript is complaining that `constants` doesn't exist on the Theme object.

There wasn't this problem with MUI v5 so I'm not sure what has changed.

Any suggestions? Thanks!

**Comment by garronej** [comment]
Hello @Canuckaholic,  

It's suppose to work. If it doesn't it can be one of two things.  

1) You're not importing from `import { } from "tss-react/mui"` but from `"tss-react"`.  
2) In the process of upgradingto MUI v6 some of your dependencies have been deduped and you have now multiple version of `@mui/material` cohexisting in your node_modules.  

The second case is much more likely. It can usually be fixed just by removing the lockfile but this might be something you are trying to avoid.  

If you show me your lockfile I should be able to tell you what's going on.

**Comment by Canuckaholic** [comment]
Thanks @garronej for replying so quickly. So I'm definitely importing `tss` from `"tss-react/mui"`. I just tried deleting my `package-lock` file and re-installing but am still getting the type error. I'll attach my lockfile here just in case.

I'll also attach the file where I do the module declaration merging. Cheers.

[package-lock.json](https://github.com/user-attachments/files/17882184/package-lock.json)
[createVidigamiTheme.txt](https://github.com/user-attachments/files/17882190/createVidigamiTheme.txt)

**Comment by garronej** [comment]
Ok. I'll look into it. What I can tell you is that it's supposed to work I just tested it to be 100% sure.  
Worst case scenario there is a workaround.

**Comment by garronej** [comment]
Hello @Canuckaholic,  

Yes so, that what I though.  
You have diffrent version of `@mui/material` cohexisting in your codebase.  
At the root of your `node_modules` you still have `@mui/material` v5 however `vidigami-ui` is using a nested `@mui/material` in version 6.  

How to fix this:  
Make sure `@mui/material` and all `@mui` modules are declared as peer depencencies of `@vidigami/ui` so that NPM knows that it should dedupe the dependency in the monorepo.  
(You can keep it as a devDep but it must also be declared as a peerDep)
You should also do the same with `@emotion` packages.  

Also, in the web project of your monorepo (vidigami-web), have a look at your package.json, you must have `"@mui/material": "^5.x.x"`, you should bump that to 6.  

You package.json of `package/vingami-ui` should look like:  

```json
      "name": "@vidigami/ui",
      "devDependencies": {
        "@emotion/react": "^11.13.5",
        "@emotion/styled": "^11.13.5",
        "@mui/icons-material": "^6.1.8",
        "@mui/material": "^6.1.8",
        "@mui/system": "^6.1.8",
        "@mui/x-data-grid": "^7.22.3",
        "@mui/x-date-pickers": "^7.22.3",
        "@vidigami/utils": "^0.0.1",
        "mui-color-input": "^5.0.1",
        "react-intersection-observer": "^9.10.3",
        "react-sticky-box": "^2.0.5",
        "simplebar-react": "^3.2.6",
        "tss-react": "^4.9.13"
      },
      "peerDependencies": {
        "@svgr/cli": "^8.1.0",
        "@emotion/react": "^11.13.5",
        "@emotion/styled": "^11.13.5",
        "@mui/material": "^6.1.7",
        "@types/react": "^18.0.0",
        "react": "^18.0.0",
        "@mui/system": "^6.1.8",
        "@mui/x-data-grid": "^7.22.3",
        "@mui/x-date-pickers": "^7.22.3",
    },
      }
```

And the package.json of `packages/vidigami-web` should look like:  

```json
{
    "name": "vidigami-web",
    "dependencies": {
        "@vingami/ui": "workspace:*",
        "@svgr/cli": "^8.1.0",
        "@emotion/react": "^11.13.5",
        "@emotion/styled": "^11.13.5",
        "@mui/material": "^6.1.7",
        "react": "^18.3.1",
        "@mui/system": "^6.1.8",
        "@mui/x-data-grid": "^7.22.3",
        "@mui/x-date-pickers": "^7.22.3",
    },
    "devDependencies": {
           "@types/react": "^18.0.0",
    }
}
```

**Comment by Canuckaholic** [comment]
Thanks! This worked. I didn't think I needed the `@mui` dependencies in the root because we are using `nx`, but I guess I do.
