### ISSUE TITLE
Hydration error founded in Nextjs15

### ISSUE THREAD

**Issue by MasterProvider** [garronej/tss-react#222]
It's been while before I got the hydration error came from

**dependencies**
```
"dependencies": {
    "@emotion/react": "^11.14.0",
    "@emotion/styled": "^11.14.0",
    "@mui/lab": "^6.0.0-beta.20",
    "@mui/material": "^6.2.1",
    "@mui/material-nextjs": "^6.2.1",
    "next": "^15.1.2",
    "react": "^19.0.0",
    "react-dom": "^19.0.0",
    "tss-react": "^4.9.14",
  },
```

**sample classes**
```
sideViewContent:{
    height:'auto',
    position:'relative',
    padding: '6.4rem',
    [theme.breakpoints.down('lg')]: {
      padding: '2.4rem',
    },
    [`& .${classes.appIcon}`]: {
      height: '70px',
      width: '70px'
    },
}
```

getting hydration error when you create a class child in tss-react

**Comment by MasterProvider** [comment]
it work when change it to


```
sideViewContent:{
    height:'auto',
    position:'relative',
    padding: '6.4rem',
    [theme.breakpoints.down('lg')]: {
      padding: '2.4rem',
    }
},
appIcon: {
      height: '70px',
      width: '70px'
},
```

It is sad that we are now unable to create a nested class name.

**Comment by jacks-sam1010** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modified the tss-react usage to address the hydration error. Updated dependencies and adjusted the class creation approach.

You can review changes in this commit: https://github.com/jacks-sam1010/garronej-tss-react-222/commit/7117768bfc1a7a3ff1f1d9433bc6ed20465178c0.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

Latta AI seeks to solve problems in open source projects as part of its mission to support developers around the world. Learn more about our mission at https://latta.ai/ourmission . If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by garronej** [comment]
Hello @MasterProvider,  

If you're using the `makeStyles` API with nested selectors and server-side rendering (SSR), you need to provide a `uniqId` to your `makeStyles`:  

👉 [Documentation on SSR with nested selectors](https://docs.tss-react.dev/nested-selectors#ssr)  

That said, I recommend switching from `makeStyles` to [the modern API](https://docs.tss-react.dev/api/tss-usestyles). The modern API offers better performance and is much easier to read and write.  

Merry Christmas! 🎄
