### ISSUE TITLE
Mui v5 component classes always take precedence

### ISSUE THREAD

**Issue by chazsolo** [garronej/tss-react#25]
Hi @garronej

First of all - thank you so much for your work - I was really worried about the direction of MUI's styling for v5.

Trying to implement tss-react as my team has moved to migrated to mui v5 but having a lot of trouble. I've been reading your documentation, the mui migration guide, issues, everything I can, but I've yet to successfully apply tss-react properly. I believe I have most things set up properly, as the styles generated are correct, but the ultimate problem is order/specificity. MUI v5 styles are the same specificity of tss-react generated ones and come after, therefore they always override what tss generates on components.

My relevant configuration:

**makeStyles.ts**

```typescript
import { createMakeStyles } from 'tss-react';

import theme from '$src/theme';

function useTheme() { return theme; }

export const { makeStyles, useStyles } = createMakeStyles({ useTheme });
```

**index.tsx**

```typescript
import { CacheProvider } from '@emotion/react';
import CssBaseline from '@mui/material/CssBaseline';
import { ThemeProvider } from '@mui/material/styles';
import { render } from 'react-dom';
import createCache from 'tss-react/@emotion/cache';

import Root from '$components/Root';
import theme from '$src/theme';

export const muiCache = createCache({
  key: 'mui', // all material ui classes start with 'css' instead of 'mui' even with this here
  prepend: true,
});

render(
  <CacheProvider value={muiCache}>
    <ThemeProvider theme={theme}>
      <CssBaseline />
      <Root />
    </ThemeProvider>
  </CacheProvider>,
  document.getElementById('root')
);
```

An example of  how I'm using it in a component:

**Banner.tsx**

```typescript
import { Typography } from '@mui/material';
import React from 'react';

import useStyles from './styles';

export default function Banner(): JSX.Element {
  const { classes } = useStyles();

  return (
    // no problems here
    <div className={classes.banner}>
      // two classes here, ".css-XX-MuiTypography-root" and ".tss-XX" but the former wins by order
      <Typography className={classes.text}>
        Banner
      </Typography>
    </div>
  );
}
```

**styles.ts**

```typescript
import { makeStyles } from '$src/makeStyles.ts';

export default makeStyles()((theme) => ({
  banner: {
    // styles here applied to a div, everything good
  },
  text: {
    // styles here conflict with mui styles coming from ".css-XX-MuiTypography-root"
  }
});
```

I don't know what I'm missing. Unfortunately it's a bit difficult for me to make a workable copy as my code is on another system. I will do my best to explain more if needed.

**Comment by garronej** [comment]
I am sorry you ran into those issue.  
I am pretty sure the bug come from the renaming of the module from `@material-ui/core` to `@mui/material` two days ago.  
I will be putting a warning at the top of the readme. And working on solving the problem. 
In the meantime you can:
`package.json`
```diff
-"@mui/material": "^5.0.3",
+"@material-ui/core": "5.0.0-beta.4"
```

**Comment by garronej** [comment]
Everything should work in [v0.9.4](https://github.com/garronej/tss-react/releases/tag/v0.9.4). Update `@mui/material`, `tss-react`, `@emotion/react` and `@emotion/styled` to the latest version in your `package.json`, remove your `.yarn.lock` file and reinstall.  
Sorry you had to go through this.

**Comment by garronej** [comment]
Just one last thing, I'd suggest you this change in your configuration:  
```diff
import { useTheme } from '@mui/material/styles';
-import theme from '$src/theme';
+import type theme from '$src/theme';

-function useTheme() { return theme; }

-export const { makeStyles, useStyles } = createMakeStyles({ useTheme });
+export const { makeStyles, useStyles } = createMakeStyles({ "useTheme": useTheme as (()=> typeof theme) });
```
It's better as you might want, in the future to implement a dark mode or something like that, with the `useTheme` hook you are supposed to pick up the contextual `theme` object that you provided using `<ThemeProvider />`

**Comment by chazsolo** [comment]
I will be able to check to see if all this works on Tuesday - I'll let you know how it goes!

**Comment by chazsolo** [comment]
We're using `npm`. I'd love to send you something but as I said it's all on a different system, I have to type out what we have by hand.

I did remove our lock file and reinstall everything, ensuring those packages are up-to-date. I will do some more investigation and let you know if I can't figure it out.

**Comment by chazsolo** [comment]
> I think it's the outdated @emotion/styled that is the source of the problem.

You were spot on - this fixed it!

**Comment by netzwerg** [comment]
First things first: Thanks for tss-react – long live makeStyles! 🎉

I've just spent more than an hour figuring out that `@emotion/styled` is a required dependency – where would be the best place to document this more prominently?

**Comment by garronej** [comment]
Hi @netzwerg,  

Sorry you had to go through this. Been there, very frustrating. I added a warning in the setup page but apparently it's not enough, I will edit.  

![image](https://user-images.githubusercontent.com/6702424/152553880-2dc2d6d4-5547-4e3d-99f2-1b651037ec35.png)

**Comment by garronej** [comment]
![image](https://user-images.githubusercontent.com/6702424/152554583-87cab46d-4622-4733-a420-949828b76933.png)

**Comment by netzwerg** [comment]
I copied the `yarn add` line, so this totally would have saved me (the warning was too far down 🙈) – thanks a lot! 🎉

**Comment by garronej** [comment]
Thanks for reporting
