### ISSUE TITLE
[Help] Support for Material Ui 5 with Javascript

### ISSUE THREAD

**Issue by Bramgus12** [garronej/tss-react#28]
I am currently using a project with Material UI 4 and am in the process of changing to MUI 5. I had used a lot of makeStyles and would like to still use this way of styling. I saw this repo and thought this would be a great way to still use makeStyles, but then saw that you guys specifically made this for TS and not JS. So I am asking if you guys support JS and if you do, how can I then add it to my project? Maybe there could be a specific guide with everything you need to do to convert your MUI 5 project to use this library?

**Comment by garronej** [comment]
Hi @Bramgus12,  
You can use TSS with a plain JavaScript problem. There isn't any specific instruction to make it work, just follow the guide in the README, just remove the type annotation whenever there is.  

Essentially:  
```diff
- const useStyles = makeStyles<{ color: "red" | "blue" }>()(
+ const useStyles = makeStyles()( 
    (theme, { color }) => ({
        "root": {
            color,
            "&:hover": {
                "backgroundColor": theme.primaryColor,
            },
        },
    }),
);

```

**Comment by kailashthakuri** [comment]
Hi, I am trying to use TSS in javascript react project. but styles written within makeStyles are getting ovverriden and are not applied correctly.
![tss-react](https://user-images.githubusercontent.com/17194118/141231856-cc2f945e-e94b-420d-bc93-7da316e00655.PNG)
