### ISSUE TITLE
How to add prefix globally?

### ISSUE THREAD

**Issue by ghost** [garronej/tss-react#29]
Hey man :)

Now we are working on a project with micro-frontend architecture based on Webpack 5 Module Federation.

It's actually a single react project made up of 20 small projects.

Just a bit worried on the duplication on CSS classnames. Is it possible that there might be some duplicated classnames across these projects?

In material UI, there's a key attribute in emotion cache, as well as the prefix attribute in JSS which can avoid this problem.

```tsx
export const muiCache = createCache({
  key: "mui",
  prepend: true
});
```

Please give us some advices, thanks mate :)

**Comment by garronej** [comment]
Hi @chengjiaapraamcos,  

You can tell `tss-react` to use a custom emotion cache. [Doc](https://github.com/garronej/tss-react#cache).  
Example:    

```tsx
import { CacheProvider } from "@emotion/react";
import { TssCacheProvider } from "tss-react";
import createCache from "@emotion/cache";

export const muiCache = createCache({
	"key": "mui",
	"prepend": true
});

export const tssCache = createCache({
	"key": "your-prefix"
});

render(
	<CacheProvider value={muiCache}>
		<TssCacheProvider value={tssCache}>
			{/* ... */}
		</TssCacheProvider>
	</CacheProvider>,
	document.getElementById("root"),
);
```

[Don't forget to update your SSR config](https://github.com/garronej/tss-react#server-side-rendering-ssr) 
```diff
- const { Document } = createDocument({ "caches": [ muiCache ] })
+ const { Document } = createDocument({ "caches": [ muiCache, tssCache1, tssCache2, /*...*/ ] });
```
