### ISSUE TITLE
Issue when using tss-react on building a customized UI library

### ISSUE THREAD

**Issue by chengjiaapraamcos** [garronej/tss-react#33]
We are upgrading the company's UI library, which is a wrapper of MUI components, and tss-react is used to customize the styles with dynamic themes. Also we use makeStyles, useStyles etc. within the UI library repository to customize the MUI styles:

```ts

   export const { makeStyles, useStyles, withStyles } = createMakeAndWithStyles({ useTheme });

```

The issue is, when consuming the customized components from the UI library from our main project, and we got this error:

```
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
```

I guess the reason is because the "useStyles" within the UI library repo does not work because it is actually a wrapper of the "useTheme" hooks, and it should be created in the main repo. However we need to use it in the UI library which is causing issue.

Any solutions can help?

**Comment by garronej** [comment]
![image](https://user-images.githubusercontent.com/6702424/140297114-c482e9e5-ed74-4d9b-bdab-873280b2181f.png)

**Comment by garronej** [comment]
I ran into this error many times myself working with [onyxia-ui](https://github.com/InseeFrLab/onyxia-ui) in [onyxai-web](https://github.com/InseeFrLab/onyxia-web).  

If you do `yarn link` in your UI module and `yarn link <your ui moduel>` you get this error at runtime.  

You also need to:  
```bash
cd <your ui library>/node_modules/react
yarn link
cd <your ui library>/node_modules/@types/react
yarn link

cd <your main app>
yarn link react @types/react
```

**Comment by garronej** [comment]
We use [a script](https://github.com/InseeFrLab/onyxia-web/blob/main/src/bin/link_inhouse_deps.ts) to automate that if you are interested.

**Comment by chengjiaapraamcos** [comment]
> I ran into this error many times myself working with [onyxia-ui](https://github.com/InseeFrLab/onyxia-ui) in [onyxai-web](https://github.com/InseeFrLab/onyxia-web).
> 
> If you do `yarn link` in your UI module and `yarn link <your ui moduel>` you get this error at runtime.
> 
> You also need to:
> 
> ```shell
> cd <your ui library>/node_modules/react
> yarn link
> cd <your ui library>/node_modules/@types/react
> yarn link
> 
> cd <your main app>
> yarn link react @types/react
> ```

Thanks for your quick reply buddy :)

Not sure whether we were talking about the same issue.

My issue is that our library is packed and published on NPM, and we use this wrapped package within our main project by installing the package through npm.

The "makeStyles", "createStyles" created within the library could not work in our main repo, as well as all the customized components. :)

Sorry for all these questions haha...

**Comment by chengjiaapraamcos** [comment]
Is there any easy way to make it working? Because most of the packages don't need to use link :)
We upgraded from V4 and V4 doesn't need link  to achieve this.

**Comment by garronej** [comment]
This should be an easy fix yes. Can I see the NPM package of your UI lib?  
Maybe you have `"react"` in dependencies instead of `"peerDependencies"`?

**Comment by chengjiaapraamcos** [comment]
> This should be an easy fix yes. Can I see the NPM package of your UI lib? Maybe you have `"react"` in dependencies instead of `"peerDependencies"`?

You are right brother, some stupids removed these lines secretly. Now working like a charm... Tons of thanks for your solution on yarn link and I will use it on local development. Really helpful and thanks for your great work!!!!!!

This is an amazing library, really well built!

**Comment by garronej** [comment]
Thank you for the kind words, much appreciated!  

If you use our script, unless you are using [TS_CI](https://github.com/garronej/ts-ci), you will need to remove [theses lines](https://github.com/InseeFrLab/onyxia-web/blob/998d264212703a9d87c6c02b2671793d1b09e0c7/src/bin/link_inhouse_deps.ts#L109-L139).  
  
Also you'll have to edit [this line](https://github.com/InseeFrLab/onyxia-web/blob/998d264212703a9d87c6c02b2671793d1b09e0c7/src/bin/link_inhouse_deps.ts#L75) and put your own libraries that you need to link.  

And of course don't forget to [add `.yarn_home`](https://github.com/InseeFrLab/onyxia-web/blob/998d264212703a9d87c6c02b2671793d1b09e0c7/.gitignore#L34) to your `.gitignore`.  

Best
