### ISSUE TITLE
Bug in cx function

### ISSUE THREAD

**Issue by olee** [garronej/tss-react#34]
If I'm not mistaken, in [this line](https://github.com/garronej/tss-react/blob/d648e316e668689d44acad66c6c5e5f717e862c6/src/cssAndCx.tsx#L201), the code should not be
```ts
.map(classNameOrCSSObject =>
    typeof classNameOrCSSObject === "string"
        ? className
        : css(classNameOrCSSObject),
)
```
but instead
```ts
.map(classNameOrCSSObject =>
    typeof classNameOrCSSObject === "string"
        ? classNameOrCSSObject
        : css(classNameOrCSSObject),
)
```

**Comment by garronej** [comment]
Hi @olee,  
Glad to see you back. 
Yes you are right! Good catch.
Do you want to submit a PR or do I fix it now?

**Comment by olee** [comment]
I think in this case it's easier you just fix it quickly 😄 
Otherwise I would have directly created a PR but I don't really want to bother right now :-P
