### ISSUE TITLE
MUI V5 precedence - nested classes?

### ISSUE THREAD

**Issue by JohnnyCrazy** [garronej/tss-react#38]
Hi there,

I'm currently trying out `tss-react` and noticed a roadblock, which I'm not sure how to solve it: I'm unable to change the color of the `deleteIcon` of a `Chip` since the original styles take precedence. I also followed the steps of the README, see here for a repro: https://stackblitz.com/edit/tss-react-aupnsq?file=Hello.tsx

As you can see, overriding the color in the theme works, but individually styling it with `withStyles` creates the wrong class order.

![image](https://user-images.githubusercontent.com/3109892/142503124-a3b33805-23b4-40d4-80a8-fe04406f63f7.png)

Am I missing something obvious? Do I maybe somehow have to specify `MuiButtonBase-root-MuiChip-root` so it it's on the same level?

**Comment by JohnnyCrazy** [comment]
Maybe related to https://github.com/mui-org/material-ui/issues/28664 and not even in the scope of `tss-react` 🤔

**Comment by garronej** [comment]
Damn it, it's not the expected behaviour indeed. Probably something that need to be addressed on the mui side though. 
I will investigate with them. 
In the meantime the only workaround I can suggest is this: https://stackblitz.com/edit/tss-react-wfuji8?file=Hello.tsx

Thank you for reporting

**Comment by garronej** [comment]
@JohnnyCrazy I confirm that the problem is on the mui side and that it is specific to the `<Chip>` component.  

Considering that maybe you can just increase specificity manually for this specific case:  

```ts
const ChipStyled = withStyles(Chip, {
    "deleteIcon": {
        "&&":{
            "color": "red"
        }
    }
});
```

It's ugly but at least it's type-safe....

**Comment by garronej** [comment]
I have opened [an issue about it](https://github.com/mui-org/material-ui/issues/29757).  

In the meantime, since it looks like to be specifically related to the `<Chip/>` component you could use `&&` to increase specificity:   
```ts
const ChipStyled= withStyles(Chip, { 
    "deleteIcon": {
        "&&":{
            "color": "red"
        }
    }
});
```

**Comment by garronej** [comment]
They it. So do I. I don't think it's up to me. Reopen if you think otherwise.

**Comment by JohnnyCrazy** [comment]
Sounds good, ty for the fast help :)
