### ISSUE TITLE
Error in latest release

### ISSUE THREAD

**Issue by TriPSs** [garronej/tss-react#42]
I get the following error when compiling my project in the latest version.

```
Module not found: Error: Can't resolve 'tsafe/typeGuard' in '/node_modules/tss-react'
```

**Comment by garronej** [comment]
Sorry about that 😬😬😬

**Comment by garronej** [comment]
Fixed

**Comment by garronej** [comment]
I've removed the dependency to [tsafe](https://github.com/garronej/tsafe) in 3.0.2
