### ISSUE TITLE
Injection order of tss and regular styles are in the wrong order for a short while

### ISSUE THREAD

**Issue by paales** [garronej/tss-react#52]
Hi there!

I'm running into an issue where the order of css and tss styles are sorted in the wrong way in the head for a short period of time..

Video of the problem: https://d.pr/v/SXxXJq

You can see it happening from the 15 second mark in the video, you see the `tss-` below the `css-` styles for a short while

It seems to be due to a reordering in the header which is happening teporarily:

https://user-images.githubusercontent.com/1244416/148525883-047b4e8d-3036-4fe9-bbaa-a661dcdaddc8.mp4

Server loaded styles:
<img width="1173" alt="Schermafbeelding 2022-01-07 om 10 49 34" src="https://user-images.githubusercontent.com/1244416/148525830-73a7e430-b2d3-4516-bf75-b9f238701b90.png">

CSS styles get applied below the tss styles:
<img width="1173" alt="Schermafbeelding 2022-01-07 om 10 49 45" src="https://user-images.githubusercontent.com/1244416/148525836-daa4c0f6-4949-4497-80fd-6ad9271cb761.png">

CSS styles are now moved to the top:
<img width="1173" alt="Schermafbeelding 2022-01-07 om 10 49 50" src="https://user-images.githubusercontent.com/1244416/148525845-09c730de-2b1a-4de0-8028-88a79a96f1be.png">

I'm using the following code:

```ts
// eslint-disable-next-line @next/next/no-document-import-in-page
import type Document from 'next/document'
import { withEmotionCache } from 'tss-react/nextJs'
import { emotionCache } from './tssReact'

export function documentWithEmotion(Doc: typeof Document) {
  return withEmotionCache({ Document: Doc, getCaches: () => [emotionCache()] })
}
```

```tsx
import createCache from '@emotion/cache'
import type { EmotionCache } from '@emotion/cache'
import { CacheProvider } from '@emotion/react'
import { getTssDefaultEmotionCache, TssCacheProvider } from 'tss-react'

let cache: EmotionCache | undefined

/** Creates a single instance of the `@emotion/cache` that is shared between server and client */
export function emotionCache() {
  if (!cache) cache = createCache({ key: 'mui', prepend: true })
  return cache
}

/** Provider that is supposed to be used in your `pages/_app.tsx` */
export function EmotionProvider({ children }: { children: React.ReactNode }) {
  return (
    <CacheProvider value={emotionCache()}>
      <TssCacheProvider value={getTssDefaultEmotionCache()}>{children}</TssCacheProvider>
    </CacheProvider>
  )
}
```

I've tried without the TssCacheProvider first, but that doesn't seem to be making a difference.

Ideas: After googling a bit we might be able to use this option to make this more stable?
https://github.com/emotion-js/emotion/issues/2037#issuecomment-984681767

(In general it bothers me a bit that it even recreates styles in the DOM, because that means that the browser _must_ reevaluate the styles, but maybe that goes away if the locations are exactly the same..)

(I promise I'm almost done bothering you with all these issues 😗)

**Comment by garronej** [comment]
Hi,

> <TssCacheProvider value={getTssDefaultEmotionCache()}>{children}</TssCacheProvider>

This is a no-op.

> let cache: EmotionCache | undefined
> /** Creates a single instance of the `@emotion/cache` that is shared between server and client */
> export function emotionCache() {
>   if (!cache) cache = createCache({ key: 'mui', prepend: true })
>   return cache
>}

This is not a correct setup for SSR. A new instance of emotion cache must be created **for every render** on the server.  
Please refer to [the documentation](https://github.com/garronej/tss-react#with-nextjs).

**Comment by paales** [comment]
@garronej I've totally misread the example and didn't create a new emotion cache for each server render.. I've now corrected it and it seems to work as expected! 

> Beside, do you use cx or something else to merge classe names?

I'm still using `clsx()` to merge multiple classes, didn't understand what the advantage was.

I've read the source code of cx and it seems it overrides any media queries here? So that it more works like inline styles? Or does it do some additional things?

**Comment by garronej** [comment]
@paales

> does it do some additional things?

Yes it absolutely do additional things! It ensures styles are overwritten in the correct order!

```tsx

const useStyles = makeStyles()({
    "blue": {
         "backgroundColor": "blue"
    },
    "red": {
        "backgroundColor": "red"
    }
});

function MyComponent(){

    const { classes, cx } = useStyles();

    return (
        <div className={cx(classes.red, classes.blue)}>Hello World</div>
    );

}

```

In this example the `<div>` will have a blue background. But if I use `cx(classes.blue, classes.red)` the `<div>` will have a red background.  

For what it does relative to media queries see [this issue](https://github.com/garronej/tss-react/issues/27).  

Best
