### ISSUE TITLE
Problem with the latest MUIv5 and classes/withStyles overrides of nested elements

### ISSUE THREAD

**Issue by synaptiko** [garronej/tss-react#62]
Hello,

when I created this PR https://github.com/garronej/tss-react/pull/54 we were still using MUIv4. We are using overrides with `classes` prop and `withStyles` of MUI components a lot and since we started migrating to MUIv5, I've noticed something strange.

I've create a demo here:
- deployed example site: https://muiv5-problem-with-classes.vercel.app/
- related code: https://github.com/synaptiko/muiv5-problem-with-classes/blob/master/src/App.tsx

I followed the recommended steps from both `tss-react` and MUI projects to eliminate issues with the setup.

The problem in a nutshell is the following, when you have a component with sub-elements and you'd like to override default styles (let's say color or background color), one would expect to use what was possible in MUIv4:
```
const StyledChip = withStyles(Chip, (theme) => ({
  root: {
    backgroundColor: theme.palette.primary.main,
    color: theme.palette.primary.contrastText,
  },
  deleteIcon: {
    color: theme.palette.primary.contrastText,
    '&:hover': {
      color: `${theme.palette.primary.contrastText}6`,
    },
  },
}));
```

But it doesn't work because of CSS selector specificity:
![image](https://user-images.githubusercontent.com/1593280/153707734-cb985a3b-919a-49f2-a043-7705ff163967.png)

The only solution I found is with:
```
const StyledChip = withStyles(Chip, (theme, _props, classes) => ({
  root: {
    backgroundColor: theme.palette.primary.main,
    color: theme.palette.primary.contrastText,
    [`& .${classes.deleteIcon}`]: {
      color: theme.palette.primary.contrastText,
      '&:hover': {
        color: `${theme.palette.primary.contrastText}6`,
      },
    },
  },
}));
```

Unfortunately it requires a lot of refactoring in our code and it's also quite hard to reason about, you need to know that you are fighting with specificity here (which I assumed that `emotion`-based solution should help to avoid).

I'm not 100% sure if it's a problem in `tss-react` itself or if it's more about how MUIv5 handles `classes` props.

**Comment by synaptiko** [comment]
I checked MUI's issues as well and the only partially related thing I found is https://github.com/mui/material-ui/issues/30727

But it's about "state" rules, while in my case I'm overriding sub-component (slot).

I also took a look on the implementation of `Chip` to see how `classes` "resolution" is implemented but I got lost in it. But I can see now that they internally generate styles with specificity 2 for the sub-components: https://github.com/mui/material-ui/blob/master/packages/mui-material/src/Chip/Chip.js#L139

But then I'm not sure why `classes` is exposed at all, if it only can add new style props. Unless I'm missing something important here :slightly_smiling_face:

**Comment by garronej** [comment]
Hi @synaptiko,  
I agree, it's a bug, but it's a MUI bug.  
There is [this other issue](https://github.com/garronej/tss-react/issues/38) about overwriting the `<Chip>` style.  
I believe it's the same underlying problem, as you can see I opened an issue but they suggested manually increasing specificity, which, I agree should not be the responsibility of the end user.   

What I could do to make you like easier is to manually increase specificity [here](https://github.com/garronej/tss-react/issues/38) but it really feels like a hack that should be addressed on the MUI side...

**Comment by garronej** [comment]
Hi @synaptiko,  

I might be able to do something about it but I am not sure. 

Is the problem that the collor in the `root` take priority over the color in delete icon?  

![image](https://user-images.githubusercontent.com/6702424/153717615-feb1e933-d4f2-4833-86cd-04040a5d76cf.png)


PS: Maybe related: https://github.com/garronej/tss-react/issues/38

**Comment by garronej** [comment]
Is it that (1) doesn’t take precedence over (2) ?  

```ts
  deleteIcon: {
    color: theme.palette.primary.contrastText, // (2)
    '&:hover': {
      color: `${theme.palette.primary.contrastText}6`, // (1)
    },
  },
```

**Comment by garronej** [comment]
OK, thank you for the extra details.  
I was making sure there isn't anything I can do for you and I am afraid this is effectively the case.  

In defense of the MUI team, if they are facing all theses specificity issues it is because they are allowing users to use `styled-component` instead of `@emotion` as underlying style engine.  [ref](https://mui.com/guides/styled-engine/#how-to-switch-to-styled-components). It makes their job 10 times harder, I am not sure it's worth it.

**Comment by garronej** [comment]
I'm interested to have the follow up on this.  
And feel free to come back if you think there is something I can do from TSS-react.
