### ISSUE TITLE
Styles insertion order with server-side rendering

### ISSUE THREAD

**Issue by dvprrsh** [garronej/tss-react#68]
I realise this issue has been mentioned previously but, I wanted to understand something.

I recently had an issue with the insertion order of styles, the base MUI styles were being inserted after the TSS styles and so, took precedence over the TSS styles. This caused issues where I was setting the display to be `flex` but the MUI Container styles default to `block` and so rendered in a top-down approach.

<img width="494" alt="Screenshot 2022-03-08 at 21 40 47" src="https://user-images.githubusercontent.com/54036124/157330128-071dccad-bc83-472b-929e-468ef43bcacd.png">

As you can see from the screenshot, the MUI Container styles are taking precedence. I tried one of the solutions recommended on another similar issue (to use `&&`) and that worked. But I then realised that the insertion order was possibly off due to the TSS emotion server coming before the MUI emotion server in the `emotionServers` array (from the docs):

```ts
const createMUICache = () =>
  createCache({
    key: "mui",
    prepend: true,
  });

....

const muiCache = createMUICache();
// sets TSS server first and then the MUI server after, meaning the MUI styles would take precedence?
const emotionServers = [getTssDefaultEmotionCache({ doReset: true }), muiCache].map(createEmotionServer);
 
.... // renders app

const css = emotionServers
    .map(({ constructStyleTagsFromChunks, extractCriticalToChunks }) => {
      const chunks = extractCriticalToChunks(html);
      return constructStyleTagsFromChunks(chunks);
    })
    .join(""); // creates the styles but the TSS ones first and then the MUI ones
```

Noticing this, I tried it again by swapping around the two servers like below, rather than using the `&&` approach:

```ts
const emotionServers = [muiCache, getTssDefaultEmotionCache({ doReset: true })].map(createEmotionServer);
```

and that then fixes the insertion order (see the image below).

<img width="493" alt="Screenshot 2022-03-08 at 21 50 34" src="https://user-images.githubusercontent.com/54036124/157331389-35735eca-3483-46d2-a450-ea9695de5ccf.png">

So, my question is just, is there a particular reason as to why the MUI emotion server should come after the TSS one, or is it fine to have the TSS one last? If so, should the docs be updated for this?

Let me know if you would like any more information, this is the only issue I have come across with TSS and I think it is an awesome package and nice to see there is still support out there for JSS approaches with MUI! :)

**Comment by garronej** [comment]
Hi @dvprrsh,  
Sorry you had to go through this.  
This is my bad, the mui caches should absolutely comes first!  
Thank for reporting the error, [I updated the documentation](https://docs.tss-react.dev/ssr/other-backends).

**Comment by dvprrsh** [comment]
@garronej no problem at all, thanks for the quick reply :)
