### ISSUE TITLE
Wrong color applied to link when overriding MUI theme

### ISSUE THREAD

**Issue by sdornan** [garronej/tss-react#77]
We have a Next.js application that we are in the midst of upgrading from MUI v4 to MUI v5 with react-tss. Part of our theme file is as follows:

```typescript
MuiLink: {
  styleOverrides: {
    root: {
      color: '#0068b5',
      textDecoration: 'none',
    },
    underlineNone: {
      color: '#f9f9f6',
    },
  },
  defaultProps: {
    underline: 'hover',
  },
},
```

In MUI v4, this color was correctly applied. However, in MUI v5 with react-tss, our link styles look like this:

<img width="324" alt="image" src="https://user-images.githubusercontent.com/563517/163267805-7d6e0ace-786a-4766-82e9-b11dd0e64886.png">

It appears that instead of replacing the original `color` CSS property the new color is simply being added as an additional property. And unfortunately, probably based on the order styles are applied, the wrong color is taking precedence over the desired color. Any ideas here?

**Comment by garronej** [comment]
Hi @sdornan,  
This is a problem with MUI, not TSS react.  
You could stop using `tss-react` you'd still get the same behaviour.  
TSS enables to override [your **custom components**'s default styles](https://docs.tss-react.dev/mui-theme-styleoverrides).  But it has no power over the MUI's component.  

There is an ongoing PR in MUI that, I think, will fix this. See: https://github.com/mui/material-ui/pull/32067

**Comment by sdornan** [comment]
Thanks for the pointer! In that case, this can be closed.

**Comment by garronej** [comment]
Hi @sdornan,  
Yet, if you could give me some aditional information.  
Is:  
<img width="138" alt="image" src="https://user-images.githubusercontent.com/6702424/163419420-e33e86fa-2f2b-49e0-be74-00a7a0d5a389.png">
Your primary collor in your MUI theme?  

 If yes, are you using MUI link like this 
```tsx
import Link from "@mui/material/Link";

<Link href="#" color="primary">Foo bar</Link>
```

If not, where does the geenish color come from?

**Comment by sdornan** [comment]
Correct, the green color is my primary color in my theme.

Since I am using Next.js, I'm using my own Link component that was adopted and customized from the Link component here: https://github.com/mui/material-ui/blob/master/examples/nextjs/src/Link.js

The customizations aren't anything of particular note, so I think that can serve as a stand-in here.

**Comment by sdornan** [comment]
Oh! I did replace `clsx` with `cx` in this part of the example component:

```typescript
const className = clsx(classNameProps, {
  [activeClassName]: router.pathname === pathname && activeClassName,
});
```

**Comment by sdornan** [comment]
Here's the full thing to make this easier:
https://gist.github.com/sdornan/ca308046d76b766758a157c1174bbe14

**Comment by garronej** [comment]
@sdornan,  
I know there are issue in MUI with the CSS priority but with this particular component (`<MuiLink/>`) I was unable to reproduce.  
The priority of the `styleOverrides` are supposed to be very low.  
If I run this code:  

```tsx
import * as React from 'react';
import Link from "@mui/material/Link";
import { createTheme, ThemeProvider } from '@mui/material/styles';
import createCache from "@emotion/cache";
import { CacheProvider } from "@emotion/react";
import { useStyles } from "tss-react/mui";

export const muiCache = createCache({
  "key": "mui",
  "prepend": true
});

const theme = createTheme({
  "components": {
    "MuiLink": {
      "styleOverrides": {
        "root": {
          "color": "green",
        },
      },
    },
  }
});

function TestComponent() {

  const { css } = useStyles();

  return (
    <React.Fragment>
      <Link href="https://example.com" >This text should be green (from theme override)</Link>
      <Link href="https://example.com" color="secondary"  >This text should be purple (from prop secondary)</Link>
      <Link href="https://example.com" color="secondary" className={css({ "color": "pink" })}>This text should be purple (from className)</Link>
    </React.Fragment>
  );

};

render(
    <CacheProvider value={muiCache}>
      <ThemeProvider theme={theme}>
        <TestComponent />
      </ThemeProvider>
    </CacheProvider>
);
```  

I get this:  
<img width="919" alt="image" src="https://user-images.githubusercontent.com/6702424/163428745-88044da5-51db-4aa1-8784-bd83ee3fab27.png">

Which is what I expect.  
Are you expecting something else?

**Comment by sdornan** [comment]
That is the result I'd except, but not the result I'm getting in my app. I'll continue to investigate and follow-up here.

**Comment by sdornan** [comment]
If I do
```typescript
MuiLink: {
  //     root: {
  //       color: '#0068b5',
  //       textDecoration: 'none',
  //     },
  styleOverrides: {
    underlineNone: {
      color: '#f9f9f6',
    },
  },
  defaultProps: {
    underline: 'hover',
    color: '#0068b5',
  },
},
```
then the styles are as I expect:
<img width="327" alt="Screen Shot 2022-04-15 at 8 24 31 AM" src="https://user-images.githubusercontent.com/563517/163576098-47a90a5b-1fb3-4283-b72b-d1cc1bc17ac1.png">

If I add back the commented out lines, then I get the doubled up color and text-decoration again. So I guess that's the solution I'll go with. I haven't had a chance to try to reproduce in a more minimal Next.js environment, but perhaps it's some sort of SSR issue.

**Comment by garronej** [comment]
Are you using react 18?

**Comment by sdornan** [comment]
React 17.0.2

**Comment by garronej** [comment]
Hi,  
Could you give a try with the latest Next.js and React version?
