### ISSUE TITLE
Add support for StyledOptions, as a last argument of `withStyles` function

### ISSUE THREAD

**Issue by matyas-igor** [garronej/tss-react#84]
This is a proposal to add the same `options` object as `styled` emotion function has, as a last argument of `withStyles` function.

### Motivation

Right now to not pass an argument down to component, I need to write:
```jsx
const RightDrawer = withStyles(
  ({
    $width,
    ...props
  }: React.ComponentProps<typeof Drawer> & { $width: number }) => (
    <Drawer {...props} />
  ),
  (theme, props) => ({
    paper: {
      ...,
    },
  })
);
```

Instead, I would like to have:
```jsx
const RightDrawer = withStyles(Drawer,
  (theme, props) => ({
    paper: {
      ...,
    },
  }),
  { shouldForwardProp: (propName: string) => !propName.startsWith("$") }
);
```

**Comment by garronej** [comment]
Hi @matyas-igor,  
I like that proposal.  
I have no time to implement it in the short therm but if you submit a PR I will happily review and merge it.

**Comment by garronej** [comment]
In the end I figured out it was imposible to type it correctly so I give up sorry.
