### ISSUE TITLE
Best place for support for migration of mui/styles to tss-react

### ISSUE THREAD

**Issue by AntonOfTheWoods** [garronej/tss-react#86]
There is a repo (`mui-rte`) that uses `@mui/styles` which makes it incompatible with React 18. I wanted to migrate to `tss-react` but am a bit lost on how to proceed due to the repo using the generic type `WithStyles`, that doesn't appear to be implemented in `tss-react` and a few other things. I'm not 100% this is an issue but can't work out how to fix.

eg. https://github.com/niuware/mui-rte/blob/master/src/components/Blockquote.tsx
```
import React, { FunctionComponent } from 'react'
import { createStyles, withStyles, WithStyles } from '@mui/styles'
import { Theme } from '@mui/material/styles'

const styles = ({ palette }: Theme) => createStyles({
    root: {
        fontStyle: "italic",
        color: palette.grey[800],
        borderLeft: `4px solid ${palette.grey.A100}`
    }
})

interface IBlockquoteProps extends WithStyles<typeof styles> {
    children?: React.ReactNode
}

const Blockquote: FunctionComponent<IBlockquoteProps> = (props) => {
    return (
        <div className={props.classes.root}>
            {props.children}
        </div>
    )
}

export default withStyles(styles, { withTheme: true })(Blockquote)
```

I can't work out from the docs how to make this compatible further than the simple stuff. Where would the best place to ask the community for help on this sort of stuff? Stackoverflow (they don't have a `tss-react` keyword)?

**Comment by garronej** [comment]
Hi @AntonOfTheWoods,  

Thank you for your willingness to port `mui-rte` to `tss-react`.  

I ported `Blockquote.tsx` for you so you can have a reference:  
- My fork: https://github.com/garronej/mui-rte/tree/tss
- The file:  https://github.com/garronej/mui-rte/blob/tss/src/components/CodeBlock.tsx  
- The diff:  https://github.com/garronej/mui-rte/commit/5cbb30d2f11a5b31654e26685fdd32f14ab82158  

In the example I use [`tsafe`](https://github.com/garronej/tsafe) but if you want to avoid adding a new dependency you can simply do:  

`const classes = props.classes!;`  

Let me know if you need further assistance

**Comment by AntonOfTheWoods** [comment]
Merci chef ! @garronej I'll give it a go. As you replied here, I'll close this as this was the help I needed to get started!
