### ISSUE TITLE
How to disable vendor prefix generation?

### ISSUE THREAD

**Issue by moghaddam01** [garronej/tss-react#91]
display: -webkit-box;
    display: -webkit-flex;
    display: -ms-flexbox;
    display: flex;

This generates extra data and very big styles tag in browser for large applications!

**Comment by garronej** [comment]
Hi again @moghaddam01,  

Yes it can be disabled by customising the cache with the `speedy` option, assuming you are using TSS alongside mui it will look something like:  

```tsx
import createCache from "@emotion/cache";
import { TssCacheProvider } from "tss-react";
import { CacheProvider } from "@emotion/react";

const muiCache = createCache({
    "key": "my-custom-prefix-for-mui",
    "prepend": true,
    "speedy": true
});

const tssCache = createCache({
    "key": "my-custom-prefix-for-tss",
    "speedy": true
});

<CacheProvider value={muiCache}>
    <TssCacheProvider value={tssCache}>
        {/* ... */}
    </TssCacheProvider>
</CacheProvider>;

```

**Comment by moghaddam01** [comment]
Many thanks @garronej !

**Comment by garronej** [comment]
Hi @moghaddam01,  

You are welcome :)  

> I think, not bad to keep the same (default) behavior like MUI package   

Disabling vendor prefix isn't the default behavior, as you can see here, is you do not explicitly provide 
an emotion cache to MUI with `<CacheProvider />`, MUI is using a cache in which the speedy option isn't enabled.  
You can take any MUIv5 example and see for yourself, vendor prefixes are generated.  

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/6702424/176366727-50fef463-17f0-4acd-a678-a7dae9d4e870.png">

Besides, the generation of those multiple instructions are ensuring cross browser consistency.  Maybe your apps are running in a very controlled environment (like Electron for example) and you don't need those alternatives rules generated but the default should remain unchanged.  

> and it's not good idea to add CacheProvider and TssCacheProvider to elements trees for them  

Are you aware that, if you are using TSS, it si mandatory to provide at least  a `<CacheProvider />` explicitly.  
I assume the codemod doesn’t do it automatically but you have to. [See ref](https://docs.tss-react.dev/readme-1).  

Best,
