### ISSUE TITLE
Not generating some css properties.

### ISSUE THREAD

**Issue by moghaddam01** [garronej/tss-react#92]
text: {
			overflow: 'hidden',
			textOverflow: 'ellipsis',
			display: '-webkit-box',
			**boxOrient: 'vertical',
			lineClamp: 2,**
		},

Library does not generate `boxOrient` and  `lineClamp` css properties!

**Comment by garronej** [comment]
Hi @moghaddam01,  

First, I would like to let you know that `tss-react` is a wrapper around [emotion](https://emotion.sh/docs/introduction).  
All this lower level stuffs are handled by emotion.  

Nevertheless you might have success with:  

```diff

 text: {
   overflow: 'hidden',
   textOverflow: 'ellipsis',
   display: '-webkit-box',
-  boxOrient: 'vertical',
+ webkitBoxOrient: 'vertical';
-  lineClamp: 2,
+ WebkitLineClamp: 2,
 },
```  

That, I assume, will generate `-webkit-box-orient`.  

There are also special case for Firefox only feature:  https://github.com/emotion-js/emotion/issues/2036

**Comment by moghaddam01** [comment]
Many thanks @garronej !

As an Idea maybe not bad to mention, It could also be ideal If consider these items in migration tool: 
`npx @mui/codemod v5.0.0/jss-to-tss-react`
