### ISSUE TITLE
[Support] MakeStyles crashes with "Can't assign to property" error

### ISSUE THREAD

**Issue by thehig** [garronej/tss-react#93]
I've recently switched from `@mui/styles` to react-tss and I'm experiencing an error:

`Uncaught TypeError: can't assign to property "label" on "ltr": not an object`

Tracking the error down I'm lead to the makeStyles.js file, line ~45

```javascript
  const cssObject = cssObjectByRuleName[ruleName];
  if (!cssObject.label) {
      cssObject.label = `${name !== undefined ? `${name}-` : ""}${ruleName}`;
  }
```

In this error case, the `ruleName` is `direction` resulting in a `cssObject` of the string `ltr`. Attempting to write to cssObject.label causes the error above.

I've checked my codebase and I'm not modifying the direction anywhere, so I don't really understand why this is happening and could really use some assistance.

Thanks

**Comment by thehig** [comment]
> Maybe rename your `.js` files into `.tsx` files just to let TypeScript tell you what's wrong.

Thats not the easiest solution in such a large codebase. The thing that bugs me is I don't set `direction` anywhere so it must be coming from the base theme

**Comment by garronej** [comment]
Not everywhere, just on some files, momentarily to see if typescript can detect an error.  

Do you use the theme `<ThemeProvider />` as described in the doc?  https://docs.tss-react.dev/readme-1  

If I could see the code I would probably be able to spot the error quickly

**Comment by garronej** [comment]
Just in cas, It may help, https://docs.tss-react.dev/page-1/withstyles

**Comment by thehig** [comment]
I tried to make a sample to demonstrate the issue I'm having, but it doesn't have the same error.

https://codesandbox.io/s/bold-bird-v2t5pc?file=/src/Component.jsx

**Comment by thehig** [comment]
I think I figured it out, I had a botched attempt at replicating the `withTheme` behavior from older MUI. Any tips on how to implement this?

**Comment by thehig** [comment]
Yup that worked! Thanks, and sorry for the bother

**Comment by garronej** [comment]
No problem, happy to help
