### ISSUE TITLE
Question: should you be able to click on a class and go to its definition?

### ISSUE THREAD

**Issue by uldisDevelop** [garronej/tss-react#94]
Should you be able to click on a class and go to its definition?

![image](https://user-images.githubusercontent.com/24841647/176399861-7b45002e-e35a-4247-980a-e85fba05bc80.png)
![image](https://user-images.githubusercontent.com/24841647/176400096-f9c4a1d2-54fb-4ad2-8529-b7b9c7e47018.png)

**Comment by uldisDevelop** [comment]
Got it,
thanks @garronej

**Comment by garronej** [comment]
You're wellcome
