### ISSUE TITLE
Please give support for extra plugins like jss-plugin-extend

### ISSUE THREAD

**Issue by milanakabari** [garronej/tss-react#99]
`const commonCss = {
    backgroundColor: 'white',
    fontSize: 14
};`

if need to use this common css in another css then

`root: {
     extend: commonCss.
     border: '1px solid gray'
}`

for more details please visit [jss-plugin-extend](https://www.npmjs.com/package/jss-plugin-extend)

**Comment by garronej** [comment]
Hi @milanakabari,  

For this usecase in perticuar there is no need for a plugin.

```typescript
const commonCss = { backgroundColor: 'white', fontSize: 14 };

root: { 
    ...commonCss,
   border: '1px solid gray'
}
```

**Comment by milanakabari** [comment]
@garronej I have tried this way and it's working
but in my case

`const tableGrid = {
    '& .MuiDataGrid-row': {
        fontSize: 13,
        backgroundColor: 'Yellow',
     },
}`


`gridRoot: {
        ...tableGrid,
        '& .MuiDataGrid-row'': {
            paddingBottom: 20,
        },
}
`

in this case base css is override and my expectation is

`{ fontSize: 13, backgroundColor: 'Yellow', paddingBottom: 20 }`

**Comment by garronej** [comment]
Hum, I see.  
I will think about how to adress this, in the meantime how about doing:  

```typescript
import deepMerge from "deepmerge";

const tableGrid = {
    '& .MuiDataGrid-row': {
        fontSize: 13,
        backgroundColor: 'Yellow',
     },
}

gridRoot: deepMerge(
    tableGrid,
    {    
        '& .MuiDataGrid-row': {
            paddingBottom: 20
        }
    }
)
}

```

**Comment by milanakabari** [comment]
Thanks @garronej this solution is worked for me
